/**
 * sslib — Blender's shader nodes as raw WGSL (`ref_images/starship.html` §3).
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * Blender's lookup3 hash, Perlin/fBm noise, white noise and the HexGrid node
 * group are transcribed as WGSL functions and injected with `wgsl()`, so the
 * procedural patterns match the Blender build texel for texel rather than
 * approximately. This is the FIRST raw-WGSL in the project — everything else
 * is TSL — and it is deliberate: TSL's own `mx_noise` is a different noise
 * basis, and swapping it in would change every material in the port.
 *
 * NOTE the difference from procgen/blenderkit/blenderNoise.ts, which ports the
 * same Blender hash as TSL nodes for the Optimus build. Two ports of one
 * source, kept apart on purpose: each reproduces the demo it came from, and
 * merging them would put one demo's pixels at the mercy of the other's edits.
 */
import { MeshPhysicalNodeMaterial, MeshStandardNodeMaterial } from 'three/webgpu'
import type { Node } from 'three/webgpu'
import {
  Fn, wgsl, wgslFn, float, vec3, uv, positionLocal, positionView,
  normalView, mix, max, abs, sign, dFdx, dFdy, cross, dot, normalize,
} from 'three/tsl'
import { DoubleSide } from 'three'

const BL = /*@__PURE__*/ wgsl(`
fn bl_rot(x: u32, k: u32) -> u32 { return (x << k) | (x >> (32u - k)); }

fn bl_final(a0: u32, b0: u32, c0: u32) -> u32 {
  var a = a0; var b = b0; var c = c0;
  c = c ^ b; c = c - bl_rot(b, 14u);
  a = a ^ c; a = a - bl_rot(c, 11u);
  b = b ^ a; b = b - bl_rot(a, 25u);
  c = c ^ b; c = c - bl_rot(b, 16u);
  a = a ^ c; a = a - bl_rot(c,  4u);
  b = b ^ a; b = b - bl_rot(a, 14u);
  c = c ^ b; c = c - bl_rot(b, 24u);
  return c;
}
fn bl_hash2(kx: u32, ky: u32) -> u32 {
  let s: u32 = 0xdeadbeefu + (2u << 2u) + 13u;
  return bl_final(s + kx, s + ky, s);
}
fn bl_hash3(kx: u32, ky: u32, kz: u32) -> u32 {
  let s: u32 = 0xdeadbeefu + (3u << 2u) + 13u;
  return bl_final(s + kx, s + ky, s + kz);
}
fn bl_hv2f(k: vec2<f32>) -> f32 {
  return f32(bl_hash2(bitcast<u32>(k.x), bitcast<u32>(k.y))) / 4294967295.0;
}
fn bl_hv3f(k: vec3<f32>) -> f32 {
  return f32(bl_hash3(bitcast<u32>(k.x), bitcast<u32>(k.y), bitcast<u32>(k.z))) / 4294967295.0;
}

fn bl_fade(t: f32) -> f32 { return t * t * t * (t * (t * 6.0 - 15.0) + 10.0); }
fn bl_neg_if(v: f32, c: u32) -> f32 { if (c != 0u) { return -v; } return v; }

fn bl_grad2(h0: u32, x: f32, y: f32) -> f32 {
  let h = h0 & 7u;
  var u = y; if (h < 4u) { u = x; }
  var t = x; if (h < 4u) { t = y; }
  let v = 2.0 * t;
  return bl_neg_if(u, h & 1u) + bl_neg_if(v, h & 2u);
}
fn bl_grad3(h0: u32, x: f32, y: f32, z: f32) -> f32 {
  let h = h0 & 15u;
  var u = y; if (h < 8u) { u = x; }
  var vt = z; if (h == 12u || h == 14u) { vt = x; }
  var v = vt; if (h < 4u) { v = y; }
  return bl_neg_if(u, h & 1u) + bl_neg_if(v, h & 2u);
}

fn bl_perlin2(p: vec2<f32>) -> f32 {
  let Xi = floor(p);
  let Xf = p - Xi;
  let u = bl_fade(Xf.x); let v = bl_fade(Xf.y);
  let X = bitcast<u32>(i32(Xi.x)); let Y = bitcast<u32>(i32(Xi.y));
  let X1 = X + 1u; let Y1 = Y + 1u;
  let x0 = Xf.x; let x1 = Xf.x - 1.0;
  let y0 = Xf.y; let y1 = Xf.y - 1.0;
  let v00 = bl_grad2(bl_hash2(X , Y ), x0, y0);
  let v10 = bl_grad2(bl_hash2(X1, Y ), x1, y0);
  let v01 = bl_grad2(bl_hash2(X , Y1), x0, y1);
  let v11 = bl_grad2(bl_hash2(X1, Y1), x1, y1);
  return mix(mix(v00, v10, u), mix(v01, v11, u), v);
}
fn bl_perlin3(p: vec3<f32>) -> f32 {
  let Xi = floor(p);
  let Xf = p - Xi;
  let u = bl_fade(Xf.x); let v = bl_fade(Xf.y); let w = bl_fade(Xf.z);
  let X = bitcast<u32>(i32(Xi.x)); let Y = bitcast<u32>(i32(Xi.y)); let Z = bitcast<u32>(i32(Xi.z));
  let X1 = X + 1u; let Y1 = Y + 1u; let Z1 = Z + 1u;
  let x0 = Xf.x; let x1 = Xf.x - 1.0;
  let y0 = Xf.y; let y1 = Xf.y - 1.0;
  let z0 = Xf.z; let z1 = Xf.z - 1.0;
  let a = mix(mix(bl_grad3(bl_hash3(X , Y , Z ), x0, y0, z0),
                  bl_grad3(bl_hash3(X1, Y , Z ), x1, y0, z0), u),
              mix(bl_grad3(bl_hash3(X , Y1, Z ), x0, y1, z0),
                  bl_grad3(bl_hash3(X1, Y1, Z ), x1, y1, z0), u), v);
  let b = mix(mix(bl_grad3(bl_hash3(X , Y , Z1), x0, y0, z1),
                  bl_grad3(bl_hash3(X1, Y , Z1), x1, y0, z1), u),
              mix(bl_grad3(bl_hash3(X , Y1, Z1), x0, y1, z1),
                  bl_grad3(bl_hash3(X1, Y1, Z1), x1, y1, z1), u), v);
  return mix(a, b, w);
}
fn bl_snoise2(p: vec2<f32>) -> f32 { return bl_perlin2(p) * 0.6616; }
fn bl_snoise3(p: vec3<f32>) -> f32 { return bl_perlin3(p) * 0.9820; }

fn bl_fbm2(p: vec2<f32>, detail: f32, roughness: f32, lacunarity: f32) -> f32 {
  var fscale = 1.0; var amp = 1.0; var maxamp = 0.0; var sum = 0.0;
  let octaves = clamp(detail, 0.0, 15.0);
  let n = i32(octaves);
  for (var i: i32 = 0; i <= n; i = i + 1) {
    sum = sum + bl_snoise2(p * fscale) * amp;
    maxamp = maxamp + amp;
    amp = amp * roughness;
    fscale = fscale * lacunarity;
  }
  let rmd = octaves - floor(octaves);
  if (rmd != 0.0) {
    let sum2 = sum + bl_snoise2(p * fscale) * amp;
    return mix(0.5 * sum / maxamp + 0.5, 0.5 * sum2 / (maxamp + amp) + 0.5, rmd);
  }
  return 0.5 * sum / maxamp + 0.5;
}
fn bl_fbm3(p: vec3<f32>, detail: f32, roughness: f32, lacunarity: f32) -> f32 {
  var fscale = 1.0; var amp = 1.0; var maxamp = 0.0; var sum = 0.0;
  let octaves = clamp(detail, 0.0, 15.0);
  let n = i32(octaves);
  for (var i: i32 = 0; i <= n; i = i + 1) {
    sum = sum + bl_snoise3(p * fscale) * amp;
    maxamp = maxamp + amp;
    amp = amp * roughness;
    fscale = fscale * lacunarity;
  }
  let rmd = octaves - floor(octaves);
  if (rmd != 0.0) {
    let sum2 = sum + bl_snoise3(p * fscale) * amp;
    return mix(0.5 * sum / maxamp + 0.5, 0.5 * sum2 / (maxamp + amp) + 0.5, rmd);
  }
  return 0.5 * sum / maxamp + 0.5;
}
fn bl_rv2(seed: f32) -> vec2<f32> {
  return vec2<f32>(100.0 + bl_hv2f(vec2<f32>(seed, 0.0)) * 100.0,
                   100.0 + bl_hv2f(vec2<f32>(seed, 1.0)) * 100.0);
}
fn bl_rv3(seed: f32) -> vec3<f32> {
  return vec3<f32>(100.0 + bl_hv2f(vec2<f32>(seed, 0.0)) * 100.0,
                   100.0 + bl_hv2f(vec2<f32>(seed, 1.0)) * 100.0,
                   100.0 + bl_hv2f(vec2<f32>(seed, 2.0)) * 100.0);
}
fn bl_tex2(co: vec2<f32>, detail: f32, roughness: f32, lacunarity: f32, distortion: f32) -> f32 {
  var p = co;
  if (distortion != 0.0) {
    p = p + vec2<f32>(bl_snoise2(p + bl_rv2(0.0)) * distortion,
                      bl_snoise2(p + bl_rv2(1.0)) * distortion);
  }
  return bl_fbm2(p, detail, roughness, lacunarity);
}
fn bl_tex3(co: vec3<f32>, detail: f32, roughness: f32, lacunarity: f32, distortion: f32) -> f32 {
  var p = co;
  if (distortion != 0.0) {
    p = p + vec3<f32>(bl_snoise3(p + bl_rv3(0.0)) * distortion,
                      bl_snoise3(p + bl_rv3(1.0)) * distortion,
                      bl_snoise3(p + bl_rv3(2.0)) * distortion);
  }
  return bl_fbm3(p, detail, roughness, lacunarity);
}
fn bl_hex(co: vec3<f32>, scale: f32) -> vec4<f32> {
  let S = vec3<f32>(1.0, 1.7320508, 1.0);
  let hf = vec3<f32>(0.5, 0.8660254, 0.0);
  let p = co / vec3<f32>(scale, scale, scale) + vec3<f32>(512.0, 512.0, 0.0);
  let a = (p - S * floor(p / S)) - hf;
  let ps = p - hf;
  let b = (ps - S * floor(ps / S)) - hf;
  var gv = a;
  if (length(a) >= length(b)) { gv = b; }
  let sc = vec3<f32>(0.02, 0.02, 1.0);
  let snap = floor((p - gv) / sc) * sc;
  let q = abs(gv);
  let d = max(q.x, dot(q, vec3<f32>(0.5, 0.8660254, 0.0)));
  return vec4<f32>(0.5 - d, bl_hv3f(snap), bl_hv3f(snap + vec3<f32>(17.3, 5.1, 3.7)), 0.0);
}
`);
const wNoise2 = /*@__PURE__*/ wgslFn(`fn bl_noise2(co: vec2<f32>, detail: f32, roughness: f32, lacunarity: f32, distortion: f32) -> f32 { return bl_tex2(co, detail, roughness, lacunarity, distortion); }`, [BL]);
const wNoise3 = /*@__PURE__*/ wgslFn(`fn bl_noise3(co: vec3<f32>, detail: f32, roughness: f32, lacunarity: f32, distortion: f32) -> f32 { return bl_tex3(co, detail, roughness, lacunarity, distortion); }`, [BL]);
export const wWhite3 = /*@__PURE__*/ wgslFn(`fn bl_white3(co: vec3<f32>) -> f32 { return bl_hv3f(co); }`, [BL]);
export const wHex    = /*@__PURE__*/ wgslFn(`fn bl_hexgrid(co: vec3<f32>, scale: f32) -> vec4<f32> { return bl_hex(co, scale); }`, [BL]);

/* Blender Noise Texture node (Scale is folded into the Mapping node upstream) */
export const N2 = (co: Node<'vec2'>, detail: number, rough: number, dist = 0.0): Node<'float'> =>
  wNoise2({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) }) as unknown as Node<'float'>;
export const N3 = (co: Node<'vec3'>, detail: number, rough: number, dist = 0.0): Node<'float'> =>
  wNoise3({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) }) as unknown as Node<'float'>;

/* Blender ColorRamp, LINEAR, greyscale stops */
export function rampF(fac: Node<'float'>, stops: Array<[number, number]>): Node<'float'> {
  let res: Node<'float'> = float(stops[0][1]);
  for (let i = 0; i < stops.length - 1; i++){
    const p0 = stops[i][0], p1 = stops[i+1][0];
    res = mix(res, float(stops[i+1][1]), fac.sub(p0).div(p1 - p0).clamp(0, 1));
  }
  return res;
}
export const madd = (a: Node<'float'>, b: number, c: Node<'float'>): Node<'float'> => a.mul(b).add(c);                 // Math > Multiply Add
export const maddC = (a: Node<'float'>, b: number, c: Node<'float'>): Node<'float'> => a.mul(b).add(c).clamp(0, 1);     // ... with Clamp

/* Blender Bump node (gpu_shader_material_bump.glsl), evaluated in view space:
   the construction is invariant under the rigid world->view transform.       */
export const blBump = /*@__PURE__*/ Fn(([height, strength, dist]: [Node<'float'>, Node<'float'>, Node<'float'>]) => {
  const N = normalize(normalView);
  const dPdx = dFdx(positionView), dPdy = dFdy(positionView);
  const Rx = cross(dPdy, N), Ry = cross(N, dPdx);
  const det = dot(dPdx, Rx);
  const surfgrad = Rx.mul(dFdx(height)).add(Ry.mul(dFdy(height)));
  const r = normalize(N.mul(abs(det)).sub(surfgrad.mul(sign(det)).mul(dist)));
  return normalize(mix(N, r, max(strength, 0.0)));
});

export const UV3 = (): Node<'vec3'> => vec3(uv().x, uv().y, 0.0);
export const OBJ = (): Node<'vec3'> => positionLocal;                            // Texture Coordinate > Object

export function newmat(name: string, spec?: number): MeshStandardNodeMaterial {
  let m: MeshStandardNodeMaterial;
  if (spec !== undefined && Math.abs(spec - 0.5) > 1e-6){
    m = new MeshPhysicalNodeMaterial();
    (m as MeshPhysicalNodeMaterial).ior = 1.5;
    (m as MeshPhysicalNodeMaterial).specularIntensity = spec / 0.5;                       // F0 = 0.08 * spec  (Blender)
  } else {
    m = new MeshStandardNodeMaterial();
  }
  m.name = name;
  m.side = DoubleSide;                                // use_backface_culling = False
  (m as MeshStandardNodeMaterial).flatShading = false;
  return m;
}
