/**
 * sslib — Blender's EVALUATED mesh, reproduced (`ref_images/starship.html`
 * §2). GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * The one structural deviation from the demo in this whole port lives at the
 * bottom of `buildGeometry`: it returns plain typed arrays rather than a
 * THREE.BufferGeometry, because the build runs on a worker thread and three.js
 * must not be imported there. The arrays are the demo's arrays, element for
 * element — `tools/starship-parity.mjs` asserts it.
 */
import { V, Vec, radians } from './mathkit'
import type { Vec3 } from './mathkit'
import type { MB } from './meshbuilder'

/** One material-slot draw range, in vertices (the geometry is non-indexed). */
export interface GeometryGroup {
  start: number
  count: number
  materialIndex: number
}

export interface GeometryPayload {
  position: Float32Array
  normal: Float32Array
  uv: Float32Array
  groups: GeometryGroup[]
  tris: number
}

/**
 * One emitted object: a filled mesh container plus how Blender was told to
 * shade it (`smooth` is the shade_auto_smooth angle in degrees, or null for
 * per-face flags) and which material slot list it indexes into.
 */
export interface BuildObject {
  name: string
  mb: MB
  smooth: number | null
  slots: readonly string[]
  pos?: Vec3
  rotZ?: number
}

function newell(Vs: Vec3[], f: number[]): Vec3 {
  let nx = 0, ny = 0, nz = 0;
  const n = f.length;
  for (let i = 0; i < n; i++){
    const a = Vs[f[i]], b = Vs[f[(i + 1) % n]];
    nx += (a[1] - b[1]) * (a[2] + b[2]);
    ny += (a[2] - b[2]) * (a[0] + b[0]);
    nz += (a[0] - b[0]) * (a[1] + b[1]);
  }
  const l = Math.hypot(nx, ny, nz);
  return l > 0 ? [nx / l, ny / l, nz / l] : [0, 0, 0];
}
function earClip(pts: Array<[number, number]>): Array<[number, number, number]> {
  const n = pts.length;
  let idx: number[] = []; for (let i = 0; i < n; i++) idx.push(i);
  const tris: Array<[number, number, number]> = [];
  const ar = (a: [number, number], b: [number, number], c: [number, number]): number => (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0]);
  let guard = 0;
  while (idx.length > 3 && guard++ < 20000){
    let clipped = false;
    for (let i = 0; i < idx.length; i++){
      const L = idx.length;
      const i0 = idx[(i - 1 + L) % L], i1 = idx[i], i2 = idx[(i + 1) % L];
      const a = pts[i0], b = pts[i1], c = pts[i2];
      if (ar(a, b, c) <= 1e-14) continue;
      let ok = true;
      for (const j of idx){
        if (j === i0 || j === i1 || j === i2) continue;
        const p = pts[j];
        if (ar(a, b, p) >= 0 && ar(b, c, p) >= 0 && ar(c, a, p) >= 0){ ok = false; break; }
      }
      if (!ok) continue;
      tris.push([i0, i1, i2]);
      idx.splice(i, 1);
      clipped = true;
      break;
    }
    if (!clipped){ for (let i = 1; i < idx.length - 1; i++) tris.push([idx[0], idx[i], idx[i+1]]); idx = []; break; }
  }
  if (idx.length === 3) tris.push([idx[0], idx[1], idx[2]]);
  return tris;
}

function triangulate(Vs: Vec3[], f: number[], nrm: Vec3): Array<[number, number, number]> {
  const n = f.length;
  if (n === 3) return [[0, 1, 2]];
  if (n === 4) return [[0, 1, 2], [0, 2, 3]];
  let nz = new Vec(nrm[0], nrm[1], nrm[2]);
  if (nz.length < 1e-12) nz = new Vec(0, 0, 1);
  const p0 = V(Vs[f[0]]);
  const e = V(Vs[f[1]]).sub(p0);
  let ax = e.sub(nz.mul(e.dot(nz)));
  if (ax.length < 1e-9){
    ax = Math.abs(nz.z) < 0.9 ? new Vec(0, 0, 1).cross(nz) : new Vec(1, 0, 0).cross(nz);
  }
  ax = ax.normalized();
  const ay = nz.cross(ax);
  const pts = f.map((vi): [number, number] => { const q = V(Vs[vi]).sub(p0); return [q.dot(ax), q.dot(ay)]; });
  return earClip(pts);
}
export function buildGeometry(mb: MB, smoothAngleDeg: number | null): GeometryPayload {
  const Vs = mb.v;

  /* --- 1. degenerate faces (MB.build) ---------------------------------- */
  const pass1: number[] = [];
  for (let i = 0; i < mb.f.length; i++){
    const f = mb.f[i];
    if (f.length < 3) continue;
    if (new Set(f).size !== f.length) continue;
    pass1.push(i);
  }
  /* --- 2. duplicate polys (mesh.validate) ------------------------------ */
  const seen = new Set<string>(), keep: number[] = [];
  for (const i of pass1){
    const key = mb.f[i].slice().sort((a, b) => a - b).join(',');
    if (seen.has(key)) continue;
    seen.add(key);
    keep.push(i);
  }

  const F = keep.map(i => mb.f[i]);
  const FUV = keep.map(i => mb.uv[i]);
  const FM = keep.map(i => mb.mat[i]);
  const auto = (smoothAngleDeg !== null && smoothAngleDeg !== undefined);
  const FS = keep.map(i => auto ? true : mb.sm[i]);
  const nf = F.length;

  const FN = new Float32Array(nf * 3);
  for (let i = 0; i < nf; i++){
    const n = newell(Vs, F[i]);
    FN[i*3] = n[0]; FN[i*3+1] = n[1]; FN[i*3+2] = n[2];
  }

  /* --- corner tables ---------------------------------------------------- */
  let totalCorners = 0;
  const loopStart = new Int32Array(nf);
  for (let i = 0; i < nf; i++){ loopStart[i] = totalCorners; totalCorners += F[i].length; }
  const cornerFace = new Int32Array(totalCorners);
  const cornerVert = new Int32Array(totalCorners);
  for (let i = 0; i < nf; i++){
    const f = F[i], s = loopStart[i];
    for (let k = 0; k < f.length; k++){ cornerFace[s+k] = i; cornerVert[s+k] = f[k]; }
  }

  /* --- edges -> sharpness ---------------------------------------------- */
  const KEY = 2097152;                     // 2^21, safe for < 2M verts / object
  const emap = new Map();
  for (let i = 0; i < nf; i++){
    const f = F[i], L = f.length;
    for (let k = 0; k < L; k++){
      const a = f[k], b = f[(k + 1) % L];
      const key = a < b ? a * KEY + b : b * KEY + a;
      const e = emap.get(key);
      if (e === undefined) emap.set(key, [i]);
      else e.push(i);
    }
  }
  const cosT = auto ? Math.cos(radians(smoothAngleDeg)) : -2.0;
  const nv = Vs.length;
  const vPairs: Array<number[] | undefined> = new Array(nv);
  for (const [key, fl] of emap){
    if (fl.length !== 2) continue;
    const f1 = fl[0], f2 = fl[1];
    if (!FS[f1] || !FS[f2]) continue;
    const d = FN[f1*3]*FN[f2*3] + FN[f1*3+1]*FN[f2*3+1] + FN[f1*3+2]*FN[f2*3+2];
    if (d < cosT) continue;                 // sharp by angle
    const a = Math.floor(key / KEY), b = key % KEY;
    (vPairs[a] || (vPairs[a] = [])).push(f1, f2);
    (vPairs[b] || (vPairs[b] = [])).push(f1, f2);
  }
  emap.clear();

  /* --- vertex -> corners (CSR) ----------------------------------------- */
  const vstart = new Int32Array(nv + 1);
  for (let c = 0; c < totalCorners; c++) vstart[cornerVert[c] + 1]++;
  for (let i = 0; i < nv; i++) vstart[i+1] += vstart[i];
  const vcorner = new Int32Array(totalCorners);
  const fill = vstart.slice(0, nv);
  for (let c = 0; c < totalCorners; c++) vcorner[fill[cornerVert[c]]++] = c;

  /* --- corner normals --------------------------------------------------- */
  const CN = new Float32Array(totalCorners * 3);
  const par = new Int32Array(64);
  const find = (p: Int32Array, i: number): number => { while (p[i] !== i) { p[i] = p[p[i]]; i = p[i]; } return i; };
  for (let v = 0; v < nv; v++){
    const s = vstart[v], e = vstart[v+1];
    const cn = e - s;
    if (cn === 0) continue;
    let P = par;
    if (cn > P.length) P = par.length < cn ? new Int32Array(cn) : par;
    if (P.length < cn) P = new Int32Array(cn);
    const local = new Map<number, number>();
    for (let i = 0; i < cn; i++){ P[i] = i; local.set(cornerFace[vcorner[s+i]], i); }
    const pl = vPairs[v];
    if (pl){
      for (let i = 0; i < pl.length; i += 2){
        const l1 = local.get(pl[i]), l2 = local.get(pl[i+1]);
        if (l1 === undefined || l2 === undefined) continue;
        const r1 = find(P, l1), r2 = find(P, l2);
        if (r1 !== r2) P[r1] = r2;
      }
    }
    const acc = new Map<number, [number, number, number]>();
    for (let i = 0; i < cn; i++){
      const c = vcorner[s+i], fi = cornerFace[c];
      if (!FS[fi]) continue;
      const f = F[fi], L = f.length, k = c - loopStart[fi];
      const pA = Vs[f[(k - 1 + L) % L]], pC = Vs[f[k]], pB = Vs[f[(k + 1) % L]];
      const e1x = pA[0]-pC[0], e1y = pA[1]-pC[1], e1z = pA[2]-pC[2];
      const e2x = pB[0]-pC[0], e2y = pB[1]-pC[1], e2z = pB[2]-pC[2];
      const l1 = Math.hypot(e1x, e1y, e1z), l2 = Math.hypot(e2x, e2y, e2z);
      let w = 0;
      if (l1 > 1e-12 && l2 > 1e-12){
        const cd = (e1x*e2x + e1y*e2y + e1z*e2z) / (l1 * l2);
        w = Math.acos(cd < -1 ? -1 : cd > 1 ? 1 : cd);
      }
      const r = find(P, i);
      let a = acc.get(r);
      if (a === undefined){ a = [0, 0, 0]; acc.set(r, a); }
      a[0] += FN[fi*3] * w; a[1] += FN[fi*3+1] * w; a[2] += FN[fi*3+2] * w;
    }
    for (const a of acc.values()){
      const l = Math.hypot(a[0], a[1], a[2]);
      if (l > 1e-20){ a[0] /= l; a[1] /= l; a[2] /= l; }
    }
    for (let i = 0; i < cn; i++){
      const c = vcorner[s+i], fi = cornerFace[c];
      if (!FS[fi]){ CN[c*3] = FN[fi*3]; CN[c*3+1] = FN[fi*3+1]; CN[c*3+2] = FN[fi*3+2]; continue; }
      const a = acc.get(find(P, i));
      if (a && (a[0] || a[1] || a[2])){ CN[c*3] = a[0]; CN[c*3+1] = a[1]; CN[c*3+2] = a[2]; }
      else { CN[c*3] = FN[fi*3]; CN[c*3+1] = FN[fi*3+1]; CN[c*3+2] = FN[fi*3+2]; }
    }
  }

  /* --- emit, grouped by material --------------------------------------- */
  const perMat = new Map<number, number>();
  for (let i = 0; i < nf; i++) perMat.set(FM[i], (perMat.get(FM[i]) || 0) + F[i].length - 2);
  const order = [...perMat.keys()].sort((a, b) => a - b);
  let total = 0; const off = new Map<number, number>();
  for (const m of order){ off.set(m, total); total += perMat.get(m)!; }

  const pos = new Float32Array(total * 9);
  const nor = new Float32Array(total * 9);
  const uvs = new Float32Array(total * 6);
  const cur = new Map<number, number>(); for (const m of order) cur.set(m, off.get(m)!);

  for (let i = 0; i < nf; i++){
    const f = F[i], s = loopStart[i], m = FM[i];
    const fu = FUV[i];
    const tris = triangulate(Vs, f, [FN[i*3], FN[i*3+1], FN[i*3+2]]);
    for (const t of tris){
      const ti = cur.get(m)!; cur.set(m, ti + 1);
      for (let j = 0; j < 3; j++){
        const k = t[j], c = s + k, vi = f[k];
        const p = Vs[vi];
        const o9 = ti * 9 + j * 3, o6 = ti * 6 + j * 2;
        pos[o9] = p[0]; pos[o9+1] = p[1]; pos[o9+2] = p[2];
        nor[o9] = CN[c*3]; nor[o9+1] = CN[c*3+1]; nor[o9+2] = CN[c*3+2];
        const q = (fu && k < fu.length) ? fu[k] : null;
        uvs[o6] = q ? q[0] : 0; uvs[o6+1] = q ? q[1] : 0;
      }
    }
  }

  // DEVIATION (the only one in the port): the demo builds a
  // THREE.BufferGeometry here. This runs on a worker thread, so it hands back
  // the same arrays as a transferable payload and the main thread wraps them.
  // Group ranges are identical — `addGroup(off*3, perMat*3, m)`.
  const groups: GeometryGroup[] = [];
  for (const m of order) groups.push({ start: off.get(m)! * 3, count: perMat.get(m)! * 3, materialIndex: m });
  return { position: pos, normal: nor, uv: uvs, groups, tris: total };
}
