/**
 * sslib — python-ish scalar and vector helpers, ported verbatim from the
 * Starship reference build (`ref_images/starship.html` §0). GENERATED by
 * tools/starship-gen.mjs; edit the generator, not this file.
 *
 * This is a DIFFERENT lineage from procgen/blenderkit: that kit ports
 * optlib.py (fitted curves, BSP booleans, bevel modifier), this one ports
 * sslib.py (a mesh builder with prisms and lathes). Both reproduce Blender,
 * neither is a rewrite of the other, and a future port should extend whichever
 * kit its own source came from.
 */

/** `[x, y]` pair — a 2-D section profile point or a lathe profile point. */
export type Vec2 = [number, number]
/** `[x, y, z]` triple — the mesh container's vertex format. */
export type Vec3 = [number, number, number]
/**
 * Anywhere the source hands over a Blender `Vector`. The demo is duck-typed
 * and passes a `Vec`, a tuple or a bare 3-list interchangeably; every consumer
 * runs it through `V()` first, so the union is the honest signature.
 */
export type Pt3 = Vec | Vec3 | number[]

export const PI = Math.PI, TAU = 2 * Math.PI;
export const sin = Math.sin, cos = Math.cos, tan = Math.tan, sqrt = Math.sqrt;
export const radians = (d: number): number => d * Math.PI / 180;

/* python round(): half-to-even */
export function pyround(x: number): number {
  const f = Math.floor(x), d = x - f;
  if (d > 0.5) return f + 1;
  if (d < 0.5) return f;
  return (f % 2 === 0) ? f : f + 1;
}

export class Vec {
  x: number
  y: number
  z: number
  constructor(x = 0, y = 0, z = 0){ this.x = x; this.y = y; this.z = z; }
  add(o: Vec): Vec { return new Vec(this.x + o.x, this.y + o.y, this.z + o.z); }
  sub(o: Vec): Vec { return new Vec(this.x - o.x, this.y - o.y, this.z - o.z); }
  mul(s: number): Vec { return new Vec(this.x * s, this.y * s, this.z * s); }
  neg(): Vec { return new Vec(-this.x, -this.y, -this.z); }
  dot(o: Vec): number { return this.x * o.x + this.y * o.y + this.z * o.z; }
  cross(o: Vec): Vec { return new Vec(this.y * o.z - this.z * o.y,
                           this.z * o.x - this.x * o.z,
                           this.x * o.y - this.y * o.x); }
  get length(): number { return Math.sqrt(this.dot(this)); }
  normalized(): Vec { const l = this.length; return l > 0 ? this.mul(1 / l) : new Vec(0, 0, 0); }
  slice2(): Vec2 { return [this.x, this.y]; }            // mathutils Vector[:2]
}
/* accepts Vec | [x,y,z] */
export function V(p: Pt3): Vec { return (p instanceof Vec) ? p : new Vec(p[0], p[1], p[2]); }
