/**
 * sslib — the mesh container and its primitives (`ref_images/starship.html`
 * §1): MeshBuilder, swept prisms with 2-D sections, and the lathe.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * Faces are n-gons with OPTIONAL per-corner UVs, a per-face smooth flag and a
 * per-face material slot — the four things Blender's `from_pydata` +
 * `shade_auto_smooth` pipeline needs. `evalmesh.ts` turns that into buffers.
 */
import { TAU, V, Vec, cos, pyround, sin, sqrt } from './mathkit'
import type { Pt3, Vec2, Vec3 } from './mathkit'

/** `prism()` options — every one is a Blender-side keyword argument. */
export interface PrismOptions {
  up?: Pt3
  cap0?: boolean
  cap1?: boolean
  mat?: number
  smooth?: boolean
  ext0?: number
  ext1?: number
  twist?: number
  scale1?: number
}

/** `lathe()` options — likewise. */
export interface LatheOptions {
  mat?: number
  cap_bottom?: boolean
  cap_top?: boolean
  smooth?: boolean
  tile_w?: number | null
  a0?: number
  a1?: number
  center?: Vec2
  flip?: boolean
  sharp_idx?: number[]
}

export class MB {
  v: Vec3[]
  f: number[][]
  uv: Array<Vec2[] | null>
  sm: boolean[]
  mat: number[]
  constructor(){ this.v = []; this.f = []; this.uv = []; this.sm = []; this.mat = []; }
  add_v(p: Pt3): number {
    if (p instanceof Vec) this.v.push([p.x, p.y, p.z]);
    else this.v.push([p[0], p[1], p[2]]);
    return this.v.length - 1;
  }
  /* add_f(idx, uv=None, smooth=False, mat=0) */
  add_f(idx: number[], uvq: Vec2[] | null = null, smooth = false, mat = 0): void {
    this.f.push(idx.slice());
    this.uv.push(uvq);
    this.sm.push(smooth);
    this.mat.push(mat);
  }
  offset(): number { return this.v.length; }
}
function _basis(p0: Pt3, p1: Pt3, up_hint: Pt3): [Vec, Vec, Vec, number] {
  const d = V(p1).sub(V(p0));
  const L = d.length;
  if (L < 1e-9) throw new Error('zero-length beam');
  const z = d.mul(1 / L);
  let up = V(up_hint);
  if (Math.abs(up.dot(z)) > 0.999) up = (Math.abs(z.z) < 0.9) ? new Vec(0, 0, 1) : new Vec(1, 0, 0);
  let x = up.cross(z);
  if (x.length < 1e-9) x = new Vec(1, 0, 0);
  x = x.normalized();
  const y = z.cross(x).normalized();
  return [x, y, z, L];
}

export function prism(mb: MB, p0: Pt3, p1: Pt3, section: Vec2[], o: PrismOptions = {}): number {
  const up     = o.up     !== undefined ? o.up     : [0, 0, 1];
  const cap0   = o.cap0   !== undefined ? o.cap0   : true;
  const cap1   = o.cap1   !== undefined ? o.cap1   : true;
  const mat    = o.mat    !== undefined ? o.mat    : 0;
  const smooth = o.smooth !== undefined ? o.smooth : false;
  const ext0   = o.ext0   !== undefined ? o.ext0   : 0.0;
  const ext1   = o.ext1   !== undefined ? o.ext1   : 0.0;
  const twist  = o.twist  !== undefined ? o.twist  : 0.0;
  const scale1 = o.scale1 !== undefined ? o.scale1 : 1.0;

  const [x, y, z] = _basis(p0, p1, up);
  const a = V(p0).sub(z.mul(ext0));
  const b = V(p1).add(z.mul(ext1));
  const n = section.length;
  const i0 = mb.offset();
  const ct = cos(twist), st = sin(twist);
  for (const [sx, sy] of section) mb.add_v(a.add(x.mul(sx)).add(y.mul(sy)));
  for (const [sx, sy] of section){
    const rx = (sx * ct - sy * st) * scale1;
    const ry = (sx * st + sy * ct) * scale1;
    mb.add_v(b.add(x.mul(rx)).add(y.mul(ry)));
  }
  for (let k = 0; k < n; k++){
    const k2 = (k + 1) % n;
    mb.add_f([i0 + k, i0 + k2, i0 + n + k2, i0 + n + k], null, smooth, mat);
  }
  if (cap0){ const r: number[] = []; for (let i = i0 + n - 1; i > i0 - 1; i--) r.push(i); mb.add_f(r, null, false, mat); }
  if (cap1){ const r: number[] = []; for (let i = i0 + n; i < i0 + 2 * n; i++) r.push(i); mb.add_f(r, null, false, mat); }
  return i0;
}
/* --- 2D section profiles ------------------------------------------------- */
export const sec_box = (w: number, h: number): Vec2[] => [[-w/2, -h/2], [w/2, -h/2], [w/2, h/2], [-w/2, h/2]];

export function sec_i(w: number, h: number, tw: number, tf: number): Vec2[] {
  const hw = w/2, hh = h/2, hb = tw/2, hf = tf;
  return [[-hw,-hh],[hw,-hh],[hw,-hh+hf],[hb,-hh+hf],[hb,hh-hf],[hw,hh-hf],
          [hw,hh],[-hw,hh],[-hw,hh-hf],[-hb,hh-hf],[-hb,-hh+hf],[-hw,-hh+hf]];
}

export function sec_tube(r: number, n = 12): Vec2[] {
  const p: Vec2[] = [];
  for (let k = 0; k < n; k++) p.push([r * cos(TAU * k / n), r * sin(TAU * k / n)]);
  return p;
}
/* --- lathe --------------------------------------------------------------- */
export function lathe(mb: MB, profile: Vec2[], segs: number, o: LatheOptions = {}): number {
  const mat        = o.mat        !== undefined ? o.mat        : 0;
  const cap_bottom = o.cap_bottom !== undefined ? o.cap_bottom : false;
  const cap_top    = o.cap_top    !== undefined ? o.cap_top    : false;
  const smooth     = o.smooth     !== undefined ? o.smooth     : true;
  const tile_w     = o.tile_w     !== undefined ? o.tile_w     : null;
  const a0         = o.a0         !== undefined ? o.a0         : 0.0;
  const a1         = o.a1         !== undefined ? o.a1         : TAU;
  const center     = o.center     !== undefined ? o.center     : [0.0, 0.0];
  const flip       = o.flip       !== undefined ? o.flip       : false;
  const sharp_idx  = o.sharp_idx  !== undefined ? o.sharp_idx  : [];

  const n = profile.length;
  const closed = Math.abs((a1 - a0) - TAU) < 1e-6;
  const ns = closed ? segs : segs + 1;
  const cx = center[0], cy = center[1];

  const vs: number[] = [0.0];
  for (let k = 1; k < n; k++){
    const dr = profile[k][0] - profile[k-1][0];
    const dz = profile[k][1] - profile[k-1][1];
    vs.push(vs[vs.length-1] + sqrt(dr*dr + dz*dz));
  }
  const us: number[] = [];
  for (let k = 0; k < n; k++){
    const r = Math.max(profile[k][0], 1e-4);
    let circ = (a1 - a0) * r;
    if (tile_w){ const ntiles = Math.max(1, pyround(circ / tile_w)); circ = ntiles * tile_w; }
    us.push(circ);
  }

  const i0 = mb.offset();
  for (let k = 0; k < n; k++){
    const r = profile[k][0], z = profile[k][1];
    for (let s = 0; s < ns; s++){
      const a = a0 + (a1 - a0) * s / segs;
      mb.add_v([cx + r * cos(a), cy + r * sin(a), z]);
    }
  }
  for (let k = 0; k < n - 1; k++){
    const m = mat;
    const sm = smooth && (sharp_idx.indexOf(k) === -1);
    const lim = closed ? ns : ns - 1;
    for (let s = 0; s < lim; s++){
      const s2 = (s + 1) % ns;
      const A = i0 + k * ns + s;
      const B = i0 + k * ns + s2;
      const C = i0 + (k + 1) * ns + s2;
      const D = i0 + (k + 1) * ns + s;
      const u0 = us[k] * s / segs;
      const u1 = us[k] * (s + 1) / segs;
      const u2 = us[k+1] * (s + 1) / segs;
      const u3 = us[k+1] * s / segs;
      let quad = [A, B, C, D];
      let uvq: Vec2[] = [[u0, vs[k]], [u1, vs[k]], [u2, vs[k+1]], [u3, vs[k+1]]];
      if (flip){ quad = quad.slice().reverse(); uvq = uvq.slice().reverse(); }
      mb.add_f(quad, uvq, sm, m);
    }
  }
  if (cap_bottom && profile[0][0] > 1e-5){
    const ring: number[] = []; for (let s = 0; s < ns; s++) ring.push(i0 + s);
    mb.add_f(flip ? ring : ring.slice().reverse(), null, false, mat);
  }
  if (cap_top && profile[n-1][0] > 1e-5){
    const ring: number[] = []; for (let s = 0; s < ns; s++) ring.push(i0 + (n - 1) * ns + s);
    mb.add_f(flip ? ring.slice().reverse() : ring, null, false, mat);
  }
  return i0;
}

/* --- profile helpers ----------------------------------------------------- */
export function ring_stack(z0: number, z1: number, r: number, ring_h: number, lip = 0.010, groove = 0.030): Vec2[] {
  const prof: Vec2[] = [[r, z0]];
  let z = z0;
  while (z + ring_h < z1 - 1e-6){
    z += ring_h;
    prof.push([r, z - groove]);
    prof.push([r + lip, z - groove * 0.5]);
    prof.push([r + lip, z + groove * 0.5]);
    prof.push([r, z + groove]);
  }
  prof.push([r, z1]);
  return prof;
}
