/**
 * The 20 node materials of the Starship / OLIT build (`ref_images/starship.html`
 * §3, `mats.py`). GENERATED by tools/starship-gen.mjs; edit the generator.
 *
 * Every one is DoubleSide, because the Blender source has
 * use_backface_culling = False and the port needs it: the TPS shell, the hot
 * stage and most lathes here are open shells whose caps were never authored.
 * Turning culling on would put holes in the vehicle, not save fill rate.
 *
 * They are lit by the park's own Mars sun and baked sky environment, not by
 * the demo's studio rig — the demo's three-light studio and its synthetic
 * equirect are NOT part of "geometry and material", and importing them would
 * mean a second sun over the valley.
 */
import type { MeshPhysicalNodeMaterial, MeshStandardNodeMaterial, Node } from 'three/webgpu'
import { float, fract, floor, max, min, mix, uv, vec2, vec3 } from 'three/tsl'
import {
  N2, N3, OBJ, UV3, blBump, madd, maddC, newmat, rampF, wHex, wWhite3,
} from '../procgen/sslib/blenderNodes'

/** Keyed by the slot names every builder's `slots` list uses. */
export type StarshipMaterials = Record<string, MeshStandardNodeMaterial>

/* ---- 1. stainless steel hull ------------------------------------------- */
function mat_steel(name: string, { ring_h = 1.83, base = 0.60, rough = 0.255,
                           tint = [1.0, 0.995, 0.985], dirt = 0.0, seed = 0.0 }: {
                           ring_h?: number, base?: number, rough?: number,
                           tint?: number[], dirt?: number, seed?: number } = {}): MeshStandardNodeMaterial {
  const m = newmat(name);
  const U = uv().x, Vv = uv().y;

  const ridx = Vv.div(ring_h);
  const wn = wWhite3({ co: vec3(floor(ridx), float(seed), float(0.0)) }) as unknown as Node<'float'>;

  const frac = fract(ridx);
  const d0 = min(frac, float(1.0).sub(frac));
  const seam = rampF(d0, [[0.0, 1.0], [0.030, 0.0]]);

  const uidx = U.add(wn.mul(7.07)).div(7.07);
  const ufr = fract(uidx);
  const ud = min(ufr, float(1.0).sub(ufr));
  const vsw = rampF(ud, [[0.0, 1.0], [0.0045, 0.0]]).mul(0.40);
  const seam2 = max(seam, vsw);

  const n_grain = N2(vec2(U.mul(340.0), Vv.mul(2.2)), 3.0, 0.62);
  const n_mot   = N2(vec2(U.mul(0.65), Vv.mul(0.42)), 5.0, 0.55, 0.35);
  const n_spk   = N2(vec2(U.mul(26.0), Vv.mul(26.0)), 8.0, 0.75);

  const r0 = madd(n_grain, 0.085, float(rough - 0.042));
  const r1 = madd(n_mot, 0.075, r0);
  const r2 = madd(wn, 0.045, r1);
  const rspk = madd(n_spk, 0.05, r2);
  m.roughnessNode = maddC(seam2, 0.26, rspk) as unknown as Node<'float'>;

  const c0 = madd(wn, 0.055, float(base - 0.027));
  const c1 = madd(n_mot, 0.05, c0);
  const c2 = maddC(seam2, -0.16, c1);
  const col = vec3(c2.mul(tint[0]), c2.mul(tint[1]), c2.mul(tint[2]));
  if (dirt > 0.0){
    const n_d = N2(vec2(U.mul(0.22), Vv.mul(0.13)), 8.0, 0.68);
    const dr = rampF(n_d, [[0.42, 1.0], [0.72, 0.0]]);
    const dcol = mix(col, vec3(0.16, 0.135, 0.12), dr);
    m.colorNode = mix(col, dcol, float(dirt)) as unknown as Node<'vec3'>;
  } else {
    m.colorNode = col as unknown as Node<'vec3'>;
  }
  m.metalnessNode = float(1.0);
  m.normalNode = blBump(madd(n_grain, 0.35, n_mot), float(0.26), float(0.09));
  return m;
}

/* ---- 2. TPS hex tiles --------------------------------------------------- */
function mat_tiles(name: string, { tile = 0.166, dark = 0.020, rough = 0.52 }: { tile?: number, dark?: number, rough?: number } = {}): MeshStandardNodeMaterial {
  const m = newmat(name, 0.26) as MeshPhysicalNodeMaterial;
  const U = uv().x, Vv = uv().y;
  const hx = wHex({ co: UV3(), scale: float(tile) }) as unknown as Node<'vec4'>;
  const edge = hx.x, rnd = hx.y, rnd2 = hx.z;

  const gap  = rampF(edge, [[0.0, 0.0], [0.055, 1.0]]);
  const gapS = rampF(edge, [[0.0, 0.0], [0.16, 1.0]]);
  const n_w = N2(vec2(U.mul(0.30), Vv.mul(0.18)), 8.0, 0.62);
  const n_f = N2(vec2(U.mul(80.0), Vv.mul(80.0)), 6.0, 0.7);

  const c0 = madd(rnd, 0.013, float(dark));
  const c1 = madd(n_w, 0.012, c0);
  const c2 = madd(n_f, 0.008, c1);
  const c3 = madd(gap, 0.55, float(0.45));
  const cf = c2.mul(c3);
  m.colorNode = vec3(cf.mul(1.0), cf.mul(0.985), cf.mul(0.965));

  const r0 = madd(rnd2, 0.16, float(rough - 0.08));
  const r1 = madd(n_f, 0.13, r0);
  const r2 = madd(n_w, 0.10, r1);
  m.roughnessNode = maddC(gapS, -0.14, r2);
  m.metalnessNode = float(0.0);

  const hgap = madd(rnd, 0.22, float(0.55)).mul(gapS);
  m.normalNode = blBump(madd(n_f, 0.16, hgap), float(0.40), float(0.016));
  return m;
}

/* ---- 3. tower structural steel ------------------------------------------ */
function mat_tower(name: string, { base = 0.052, rough = 0.66, rust = 0.5, metal = 0.55 }: { base?: number, rough?: number, rust?: number, metal?: number } = {}): MeshStandardNodeMaterial {
  const m = newmat(name);
  const g = OBJ();
  const n1 = N3(g.mul(0.55), 9.0, 0.62, 0.4);
  const n2 = N3(g.mul(6.5),  8.0, 0.72);
  const n3 = N3(g.mul(0.11), 6.0, 0.5, 0.6);

  const rmix = rampF(n1, [[0.44, 0.0], [0.66, 1.0]]).mul(rust);
  const bc = madd(n2, 0.014, madd(n3, 0.030, float(base)));
  const grey = vec3(bc.mul(1.0), bc.mul(0.985), bc.mul(0.955));
  m.colorNode = mix(grey, vec3(0.085, 0.043, 0.021), rmix);

  const r1 = madd(n1, 0.13, madd(n2, 0.18, float(rough - 0.09)));
  m.roughnessNode = maddC(rmix, 0.16, r1);
  m.metalnessNode = maddC(rmix, -0.42, float(metal));
  m.normalNode = blBump(madd(n2, 0.6, n1), float(0.30), float(0.05));
  return m;
}

/* ---- 4. raptor engine metal --------------------------------------------- */
function mat_engine(name: string, { base = 0.075, rough = 0.34, warm = 0.0 }: { base?: number, rough?: number, warm?: number } = {}): MeshStandardNodeMaterial {
  const m = newmat(name);
  const g = OBJ();
  const n1 = N3(g.mul(2.4), 8.0, 0.6);
  const n2 = N3(g.mul(26.0), 6.0, 0.7);
  const c2 = madd(n2, 0.018, madd(n1, 0.045, float(base)));
  const tint = [1.0, 0.94 + 0.05 * (1 - warm), 0.88 + 0.10 * (1 - warm)];
  m.colorNode = vec3(c2.mul(tint[0]), c2.mul(tint[1]), c2.mul(tint[2]));
  m.roughnessNode = maddC(n1, 0.12, madd(n2, 0.16, float(rough - 0.08)));
  m.metalnessNode = float(1.0);
  m.normalNode = blBump(n2, float(0.22), float(0.02));
  return m;
}

/* ---- 5. concrete --------------------------------------------------------- */
function mat_concrete(name: string, { base = 0.30, rough = 0.85 }: { base?: number, rough?: number } = {}): MeshStandardNodeMaterial {
  const m = newmat(name, 0.13) as MeshPhysicalNodeMaterial;
  const g = OBJ();
  const n1 = N3(g.mul(0.30), 10.0, 0.65, 0.3);
  const n2 = N3(g.mul(3.2),   9.0, 0.7);
  const n3 = N3(g.mul(26.0),  6.0, 0.6);
  const c3 = madd(n3, 0.022, madd(n2, 0.045, madd(n1, 0.085, float(base - 0.042))));
  const stain = rampF(n1, [[0.30, 1.0], [0.56, 0.0]]);
  const c4 = maddC(stain, -base * 0.55, c3);
  m.colorNode = vec3(c4.mul(1.0), c4.mul(0.982), c4.mul(0.948));
  m.roughnessNode = maddC(n2, 0.10, float(rough - 0.05));
  m.metalnessNode = float(0.0);
  m.normalNode = blBump(madd(n3, 0.5, n2), float(0.45), float(0.06));
  return m;
}

/* ---- 7. flat / painted helpers ------------------------------------------ */
function mat_flat(name: string, col: number[], rough = 0.55, metal = 0.0, spec = 0.5): MeshStandardNodeMaterial {
  const m = newmat(name, spec) as MeshPhysicalNodeMaterial;
  m.colorNode = vec3(col[0], col[1], col[2]);
  m.roughnessNode = float(rough);
  m.metalnessNode = float(metal);
  return m;
}
function mat_painted(name: string, col: number[], rough = 0.5, metal = 0.1, wear = 0.35, scale = 1.5): MeshStandardNodeMaterial {
  const m = newmat(name);
  const g = OBJ();
  const n1 = N3(g.mul(scale), 9.0, 0.6);
  const n2 = N3(g.mul(scale * 14), 6.0, 0.7);
  const wmul = rampF(n1, [[0.45, 0.0], [0.68, 1.0]]).mul(wear);
  m.colorNode = mix(vec3(col[0], col[1], col[2]), vec3(0.05, 0.04, 0.035), wmul);
  m.roughnessNode = maddC(n2, 0.16, float(rough - 0.08));
  m.metalnessNode = float(metal);
  m.normalNode = blBump(n2, float(0.18), float(0.02));
  return m;
}

export function buildStarshipMaterials(): StarshipMaterials {
  const M: StarshipMaterials = {};
  M.steel       = mat_steel('Steel_Hull',   { base: 0.60,  rough: 0.245, dirt: 0.0 });
  M.steel_ship  = mat_steel('Steel_Ship',   { base: 0.615, rough: 0.235, dirt: 0.0, seed: 3.7 });
  M.steel_dirty = mat_steel('Steel_Sooted', { base: 0.44,  rough: 0.34,  dirt: 0.55, seed: 8.1 });
  M.steel_hot   = mat_steel('Steel_HotStage', { base: 0.40, rough: 0.40,
                                                tint: [1.0, 0.93, 0.85], dirt: 0.35, seed: 11.2 });
  M.tiles       = mat_tiles('TPS_Tiles',      { tile: 0.205, dark: 0.0165, rough: 0.575 });
  M.tiles_nose  = mat_tiles('TPS_Tiles_Nose', { tile: 0.205, dark: 0.0180, rough: 0.60 });
  M.tower       = mat_tower('Tower_Steel',      { base: 0.058, rough: 0.645, rust: 0.22, metal: 0.64 });
  M.tower_dark  = mat_tower('Tower_Steel_Dark', { base: 0.040, rough: 0.695, rust: 0.18, metal: 0.58 });
  M.gridfin     = mat_engine('GridFin_Steel', { base: 0.105, rough: 0.435, warm: 0.25 });
  M.engine      = mat_engine('Raptor_Metal',  { base: 0.070, rough: 0.335 });
  M.engine_hot  = mat_engine('Raptor_Nozzle', { base: 0.048, rough: 0.30, warm: 0.65 });
  M.concrete    = mat_concrete('Concrete',      { base: 0.088, rough: 0.90 });
  M.concrete_dk = mat_concrete('Concrete_Dark', { base: 0.050, rough: 0.84 });
  M.black      = mat_flat('Matte_Black', [0.018, 0.018, 0.019], 0.62, 0.25);
  M.dark_metal = mat_flat('Dark_Metal',  [0.045, 0.045, 0.048], 0.42, 1.0);
  M.grate      = mat_flat('Grating',     [0.038, 0.036, 0.034], 0.72, 0.75);
  M.white      = mat_flat('White_Paint', [0.60, 0.60, 0.585],   0.44, 0.0);
  M.orange     = mat_painted('Orange_Paint', [0.42, 0.115, 0.012], 0.46, 0.08, 0.30, 2.5);
  M.yellow     = mat_painted('Yellow_Paint', [0.42, 0.30, 0.02],  0.48, 0.05, 0.35, 2.5);
  M.glass      = mat_flat('Glass_Dark', [0.02, 0.025, 0.03], 0.12, 0.0, 0.85);
  return M;
}
