/**
 * The stack — `ref_images/starship.html` §8, `assemble.py`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * ORDER MATTERS AND IS THE SOURCE'S. `pad_geom()` gives the catch pad's seat
 * on the arm; the vehicle's X follows from it; the arm's height then follows
 * from where the ship's forward flap underside passes that seat. Only after
 * both are written back into TW may `towerBuild()` run — it reads them.
 */
import { OLM, olmBuild } from './parts/olm'
import { TW, pad_geom, towerBuild } from './parts/tower'
import { BST, boosterBuild } from './parts/booster'
import { SHIP, hull_r, shipBuild } from './parts/ship'
import { radians, tan } from '../procgen/sslib/mathkit'
import type { BuildObject } from '../procgen/sslib/evalmesh'

export interface StarshipAssembly {
  objs: BuildObject[]
  VEH_X: number
  ARM_Z: number
  SHIP_Z: number
  DECK: number
}

export function assembleStarship(): StarshipAssembly {
  const DECK = OLM.DECK_Z;
  const SHIP_Z = DECK + BST.BOOST_H - 0.06;
  const SHIP_YAW = -90.0;

  const [pad_x, pad_y, pad_ztop_rel] = pad_geom(TW.PAD_SEAT, 1);
  const VEH_X = pad_x;

  const flap_underside = (y_abs: number): number => {
    const z0 = SHIP.FWD_FLAP.z_bot, chord = SHIP.FWD_FLAP.chord;
    const hinge = hull_r(z0) + 0.10;
    const u = Math.min(Math.max((y_abs - hinge) / chord, 0.0), 1.0);
    return z0 + u * chord * tan(radians(SHIP.FWD_FLAP.bot_sweep_deg));
  };
  const ARM_Z = SHIP_Z + flap_underside(Math.abs(pad_y)) - pad_ztop_rel;

  TW.ARM_Z = ARM_Z;
  TW.VEHICLE_X = VEH_X;

  const objs: BuildObject[] = [];
  for (const o of shipBuild()){    o.pos = [VEH_X, 0, SHIP_Z]; o.rotZ = radians(SHIP_YAW); objs.push(o); }
  for (const o of boosterBuild()){ o.pos = [VEH_X, 0, DECK];  objs.push(o); }
  for (const o of towerBuild())    objs.push(o);
  for (const o of olmBuild()){
    if (o.name === 'OLM_Table' || o.name === 'OLM_BQD') o.pos = [VEH_X, 0, 0];
    objs.push(o);
  }
  return { objs, VEH_X, ARM_Z, SHIP_Z, DECK };
}
