/**
 * Super Heavy (the booster) — `ref_images/starship.html` §5, `booster.py`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 */
import { MB, lathe, prism, ring_stack, sec_box, sec_tube } from '../../procgen/sslib/meshbuilder'
import { PI, TAU, Vec, cos, pyround, radians, sin, sqrt } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'
import { raptor, surface_patch } from './ship'

/**
 * BOOST_H etc. come from the literal; BODY_TOP is assigned on the next source
 * line. The assertion is what lets the demo's two-step stay two steps — the
 * numbers themselves are checked by tools/starship-parity.mjs, not by tsc.
 */
interface BoosterConfig {
  R: number
  BOOST_H: number
  HS_H: number
  RING: number
  SEG: number
  GF_Z: number
  GF_N: number
  GF_AZ0: number
  CH_Z: number
  BODY_TOP: number
}

export const BST = { R: 4.5, BOOST_H: 71.0, HS_H: 1.92, RING: 1.83, SEG: 192,
              GF_Z: 65.30, GF_N: 4, GF_AZ0: 45.0, CH_Z: 61.20 } as BoosterConfig;
BST.BODY_TOP = BST.BOOST_H - BST.HS_H;

function booster_hull_profile(): Vec2[] {
  const R = BST.R;
  let p: Vec2[] = [[R - 0.14, 0.0], [R - 0.14, 0.05], [R, 0.16]];
  p = p.concat(ring_stack(0.16, BST.BODY_TOP, R, BST.RING, 0.005, 0.014).slice(1));
  p.push([R, BST.BODY_TOP + 0.02]);
  p.push([R + 0.05, BST.BODY_TOP + 0.06]);
  return p;
}

function hot_stage(mb: MB, z0: number, m_ring: number, m_lat: number, m_dark: number, n_zig = 24, seg = BST.SEG): void {
  const R = BST.R, HS_H = BST.HS_H;
  const ro = R + 0.055;
  lathe(mb, [[R, z0 - 0.10], [ro, z0 - 0.02], [ro, z0 + 0.40], [ro - 0.02, z0 + 0.46]],
        seg, { mat: m_ring, smooth: true });
  lathe(mb, [[ro - 0.02, z0 + 1.42], [ro, z0 + 1.50], [ro, z0 + HS_H], [R - 0.06, z0 + HS_H]],
        seg, { mat: m_ring, smooth: true });
  lathe(mb, [[R - 0.34, z0 + 0.30], [R - 0.34, z0 + 1.60]], Math.floor(seg / 2),
        { mat: m_dark, smooth: true });
  const dome: Vec2[] = [];
  for (let k = 0; k <= 12; k++){
    const t = (PI / 2) * k / 12;
    dome.push([(R - 0.34) * cos(t), z0 + 0.15 + 1.05 * sin(t)]);
  }
  lathe(mb, dome, Math.floor(seg / 2), { mat: m_dark, smooth: true });

  const zb = z0 + 0.44, zt = z0 + 1.46;
  const bw = 0.20, bt = 0.115;
  for (let k = 0; k < n_zig; k++){
    const a0 = TAU * k / n_zig, a1 = TAU * (k + 0.5) / n_zig, a2 = TAU * (k + 1) / n_zig;
    const p0: Vec3 = [ro * cos(a0), ro * sin(a0), zb];
    const p1: Vec3 = [ro * cos(a1), ro * sin(a1), zt];
    const p2: Vec3 = [ro * cos(a2), ro * sin(a2), zb];
    for (const [pa, pb] of [[p0, p1], [p1, p2]]){
      const up: Vec3 = [cos((a0 + a2) / 2), sin((a0 + a2) / 2), 0.0];
      prism(mb, pa, pb, sec_box(bw, bt), { up, mat: m_lat, smooth: false });
    }
    prism(mb, [p0[0], p0[1], zb - 0.02], [p0[0], p0[1], zb + 0.30],
          sec_box(0.16, 0.11), { up: [cos(a0), sin(a0), 0], mat: m_lat });
  }
}

function grid_fin(mb: MB, az_deg: number, z: number, m_frame: number, m_lat: number, _m_dark: number,
                  span = 4.35, width = 3.90, thick = 0.74, roll = 0.0, r_in: number | null = null): void {
  const R = BST.R;
  const a = radians(az_deg);
  const rad = new Vec(cos(a), sin(a), 0.0);
  const tng = new Vec(-sin(a), cos(a), 0.0);
  const up = new Vec(0, 0, 1);
  const rr = radians(roll);
  const wv = tng.mul(cos(rr)).add(up.mul(sin(rr))).normalized();
  const tv = up.mul(cos(rr)).sub(tng.mul(sin(rr))).normalized();
  const r0 = r_in ? r_in : R + 0.42;
  const origin = rad.mul(r0).add(up.mul(z));
  const P = (s: number, w: number): Vec => origin.add(rad.mul(s)).add(wv.mul(w));

  const hw = width / 2;
  const fw = 0.27;
  for (const w of [hw - fw / 2, -hw + fw / 2])
    prism(mb, P(0.0, w), P(span, w), sec_box(fw, thick), { up: tv, mat: m_frame, smooth: false });
  for (const s of [span - fw / 2, fw / 2])
    prism(mb, P(s, -hw + fw), P(s, hw - fw), sec_box(fw, thick), { up: tv, mat: m_frame, smooth: false });

  const cell = 0.455, tlat = 0.048;
  const nw = Math.max(2, pyround((width - 2 * fw) / cell));
  const ns = Math.max(2, pyround((span - 2 * fw) / cell));
  for (let i = 1; i < nw; i++){
    const w = -hw + fw + (width - 2 * fw) * i / nw;
    prism(mb, P(fw * 0.6, w), P(span - fw * 0.6, w), sec_box(tlat, thick * 0.90),
          { up: tv, mat: m_lat, smooth: false });
  }
  for (let i = 1; i < ns; i++){
    const s = fw + (span - 2 * fw) * i / ns;
    prism(mb, P(s, -hw + fw * 0.6), P(s, hw - fw * 0.6), sec_box(tlat, thick * 0.90),
          { up: tv, mat: m_lat, smooth: false });
  }
  prism(mb, rad.mul(R - 0.20).add(up.mul(z)), origin.add(rad.mul(0.55)), sec_tube(0.44, 20),
        { up, mat: m_frame, smooth: true });
  prism(mb, origin.add(rad.mul(0.10)), origin.add(rad.mul(0.85)), sec_tube(0.62, 16),
        { up: tv, mat: m_frame, smooth: true });
}

function blister(mb: MB, az_deg: number, z: number, mat: number, hgt: number, wid: number, out: number, pz = 0.62, pa = 0.55, NZ = 14, NA = 20, z_bias = 0.0): void {
  const R = BST.R;
  const a = radians(az_deg);
  const rows: number[][] = [];
  for (let i = 0; i <= NZ; i++){
    const t = -1.0 + 2.0 * i / NZ;
    const zz = z + t * hgt / 2;
    let ez = Math.abs(t) < 1 ? (1.0 - Math.pow(Math.abs(t), 1.0 / pz)) : 0.0;
    ez = Math.pow(Math.max(ez, 0.0), pz);
    const row: number[] = [];
    for (let j = 0; j <= NA; j++){
      const s = -1.0 + 2.0 * j / NA;
      let ea = Math.abs(s) < 1 ? (1.0 - Math.pow(Math.abs(s), 1.0 / pa)) : 0.0;
      ea = Math.pow(Math.max(ea, 0.0), pa);
      const b = out * ez * ea;
      const da = (wid / 2 / R) * s;
      row.push(mb.add_v([(R + b) * cos(a + da), (R + b) * sin(a + da), zz + z_bias * b]));
    }
    rows.push(row);
  }
  for (let i = 0; i < NZ; i++)
    for (let j = 0; j < NA; j++)
      mb.add_f([rows[i][j], rows[i][j+1], rows[i+1][j+1], rows[i+1][j]],
               [[0,0],[1,0],[1,1],[0,1]], true, mat);
}

const gf_fairing = (mb: MB, az_deg: number, z: number, mat: number): void =>
  blister(mb, az_deg, z, mat, 4.10, 3.60, 0.34, 0.78, 0.68);

function chine(mb: MB, az_deg: number, z: number, mat: number, ln = 5.40, out = 0.62, wid = 1.90): void {
  const R = BST.R;
  const a = radians(az_deg);
  const NZ = 18, NA = 6;
  const rows: number[][] = [];
  for (let i = 0; i <= NZ; i++){
    const t = i / NZ;
    const zz = z - ln * 0.62 + ln * t;
    const env = Math.pow(Math.min(t / 0.30, 1.0), 0.85) * Math.pow(Math.min((1 - t) / 0.42, 1.0), 1.25);
    const row: number[] = [];
    for (let j = 0; j <= NA; j++){
      const s = -1.0 + 2.0 * j / NA;
      const b = out * env * Math.pow(1.0 - Math.abs(s), 0.85);
      const da = (wid / 2 / R) * s;
      row.push(mb.add_v([(R + 0.008 + b) * cos(a + da), (R + 0.008 + b) * sin(a + da), zz]));
    }
    rows.push(row);
  }
  for (let i = 0; i < NZ; i++)
    for (let j = 0; j < NA; j++)
      mb.add_f([rows[i][j], rows[i][j+1], rows[i+1][j+1], rows[i+1][j]],
               [[0,0],[1,0],[1,1],[0,1]],
               !(j === (NA / 2 - 1) || j === (NA / 2)), mat);
}

function raceway(mb: MB, az_deg: number, z0: number, z1: number, w: number, bul: number, mat: number, n = 12): void {
  const R = BST.R;
  const a0 = radians(az_deg);
  const rows: number[][] = [];
  for (const z of [z0, z1]){
    const row: number[] = [];
    for (let k = 0; k <= n; k++){
      const aa = a0 - (w / R) / 2 + (w / R) * k / n;
      const b = bul * Math.pow(sqrt(Math.max(0.0, 1 - (2 * k / n - 1) ** 2)), 0.7);
      row.push(mb.add_v([(R + 0.012 + b) * cos(aa), (R + 0.012 + b) * sin(aa), z]));
    }
    rows.push(row);
  }
  for (let k = 0; k < n; k++)
    mb.add_f([rows[0][k], rows[0][k+1], rows[1][k+1], rows[1][k]],
             [[0,0],[.2,0],[.2,1],[0,1]], true, mat);
  mb.add_f(rows[0].slice().reverse(), null, false, mat);
  mb.add_f(rows[1].slice(), null, false, mat);
}

export function boosterBuild(): BuildObject[] {
  const B_ST = 0, B_HOT = 2, B_BLK = 3, B_ENG = 4, B_NOZ = 5, B_DKM = 6, B_GF = 7;  /* slot 1 (steel_dirty) is in the list below but no face uses it */
  const slots = ['steel', 'steel_dirty', 'steel_hot', 'black', 'engine', 'engine_hot', 'dark_metal', 'gridfin'];
  const R = BST.R;
  const objs: BuildObject[] = [];
  let mb: MB;

  mb = new MB();
  lathe(mb, booster_hull_profile(), BST.SEG, { mat: B_ST, smooth: true, tile_w: 0.205 });
  objs.push({ name: 'Booster_Hull', mb, smooth: 18, slots });

  mb = new MB();
  hot_stage(mb, BST.BODY_TOP, B_HOT, B_HOT, B_BLK);
  objs.push({ name: 'Booster_HotStage', mb, smooth: 36, slots });

  mb = new MB();
  for (let k = 0; k < BST.GF_N; k++){
    const az = BST.GF_AZ0 + 360.0 * k / BST.GF_N;
    gf_fairing(mb, az, BST.GF_Z, B_ST);
    grid_fin(mb, az, BST.GF_Z, B_GF, B_GF, B_BLK);
  }
  objs.push({ name: 'Booster_GridFins', mb, smooth: 30, slots });

  mb = new MB();
  for (let k = 0; k < 4; k++) chine(mb, BST.GF_AZ0 + 45.0 + 90.0 * k, BST.CH_Z, B_ST);
  objs.push({ name: 'Booster_Chines', mb, smooth: 34, slots });

  mb = new MB();
  const zb = 2.42, ez = 0.62;
  for (const [n, r, off] of [[3, 1.00, 0.0], [10, 2.66, 18.0], [20, 3.90, 0.0]] as Array<[number, number, number]>)
    for (let k = 0; k < n; k++){
      const a = TAU * k / n + radians(off);
      raptor(mb, r * cos(a), r * sin(a), zb, ez, 3.10, B_ENG, B_NOZ, 24);
    }
  lathe(mb, [[0.0, zb + 0.42], [4.30, zb + 0.42], [4.30, zb + 0.70]], 96, { mat: B_DKM, smooth: false });
  lathe(mb, [[R - 0.14, 0.02], [R - 0.30, 0.10], [R - 0.30, zb + 0.5]], 96, { mat: B_DKM, smooth: true });
  objs.push({ name: 'Booster_Engines', mb, smooth: 30, slots });

  mb = new MB();
  raceway(mb, 0.0, 3.0, BST.BODY_TOP - 1.0, 0.72, 0.24, B_ST);
  raceway(mb, 12.0, 4.0, BST.BODY_TOP - 3.0, 0.36, 0.13, B_ST);
  raceway(mb, 350.0, 5.0, 62.0, 0.30, 0.11, B_ST);
  for (const [aa, zz, w, h] of [[100, 6.0, 1.2, 1.5], [190, 10.0, 1.0, 1.3],
                                [280, 40.0, 0.9, 1.1], [150, 55.0, 0.9, 1.1],
                                [25, 30.0, 0.8, 1.0], [60, 18.5, 0.9, 1.15],
                                [245, 24.0, 0.85, 1.05], [320, 50.0, 0.8, 1.0]])
    surface_patch(mb, radians(aa) + PI / 2, zz, w, h, R, 0.040, B_DKM);
  objs.push({ name: 'Booster_Details', mb, smooth: 34, slots });

  return objs;
}
