/**
 * The Orbital Launch Mount and its pad slab — `ref_images/starship.html` §7,
 * `olm.py`. GENERATED by tools/starship-gen.mjs; edit the generator.
 */
import { MB, lathe, prism, sec_box, sec_tube } from '../../procgen/sslib/meshbuilder'
import { TAU, cos, radians, sin } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'
import { railing } from './tower'

export const OLM = { DECK_Z: 20.60, TABLE_BOT: 17.90, LEG_N: 6, R_DECK: 10.30, R_HOLE: 4.86, PLAT_Z: 1.30 };

export function olmBuild(): BuildObject[] {
  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3, T_CONC = 4, T_CONCD = 5,
        T_BLK = 6, T_SOOT = 7;  /* slots 8 (orange) and 9 (white) are in the list below but no face uses them */
  const slots = ['tower', 'tower_dark', 'grate', 'dark_metal', 'concrete', 'concrete_dk',
                 'black', 'steel_dirty', 'orange', 'white'];
  const { DECK_Z, TABLE_BOT, LEG_N, R_DECK, R_HOLE, PLAT_Z } = OLM;
  const objs: BuildObject[] = [];
  let mb: MB;

  /* -------- launch table -------- */
  mb = new MB();
  lathe(mb, [[R_DECK - 0.55, TABLE_BOT - 1.55], [R_DECK, TABLE_BOT - 0.85],
             [R_DECK, DECK_Z - 0.28], [R_DECK + 0.22, DECK_Z - 0.10],
             [R_DECK + 0.22, DECK_Z]], 72, { mat: T_DARK, smooth: true });
  lathe(mb, [[R_DECK + 0.22, DECK_Z], [R_HOLE + 0.35, DECK_Z]], 72, { mat: T_GRATE, smooth: false });
  lathe(mb, [[R_HOLE + 0.35, DECK_Z], [R_HOLE, DECK_Z - 0.45], [R_HOLE, TABLE_BOT - 2.6]], 72,
        { mat: T_SOOT, smooth: true });
  lathe(mb, [[R_HOLE, TABLE_BOT - 2.6], [R_DECK - 0.55, TABLE_BOT - 1.55]], 72,
        { mat: T_DKM, smooth: false });
  for (let k = 0; k < 20; k++){
    const a = TAU * k / 20;
    const x = (R_HOLE + 0.62) * cos(a), y = (R_HOLE + 0.62) * sin(a);
    prism(mb, [x, y, DECK_Z - 0.05], [x, y, DECK_Z + 1.05], sec_box(0.62, 0.50),
          { up: [cos(a), sin(a), 0], mat: T_DKM, smooth: false });
  }
  for (let k = 0; k < 12; k++){
    const a = TAU * k / 12 + 0.26;
    const r = R_DECK - 1.5;
    const x = r * cos(a), y = r * sin(a);
    const h = 1.1 + 0.65 * ((k * 7) % 5) / 5.0;
    prism(mb, [x, y, DECK_Z], [x, y, DECK_Z + h], sec_box(1.5, 1.1),
          { up: [cos(a), sin(a), 0], mat: (k % 3) ? T_DKM : T_MAIN, smooth: false });
  }
  const pts: Vec2[] = [];
  for (let k = 0; k < 40; k++)
    pts.push([(R_DECK + 0.05) * cos(TAU * k / 40), (R_DECK + 0.05) * sin(TAU * k / 40)]);
  railing(mb, pts, DECK_Z + 0.05, 1.15, T_MAIN, 1.7);

  for (let k = 0; k < LEG_N; k++){
    const a = TAU * k / LEG_N + radians(30);
    const rt = 7.85, rb = 9.95;
    const top: Vec3 = [rt * cos(a), rt * sin(a), TABLE_BOT - 0.5];
    const bot: Vec3 = [rb * cos(a), rb * sin(a), PLAT_Z];
    prism(mb, bot, top, sec_tube(1.28, 26), { up: [0, 0, 1], mat: T_DARK, smooth: true, scale1: 1.10 });
    prism(mb, [bot[0], bot[1], PLAT_Z], [bot[0], bot[1], PLAT_Z + 0.68], sec_box(3.5, 3.5),
          { up: [cos(a), sin(a), 0], mat: T_DKM, smooth: false });
    const a2 = TAU * ((k + 1) % LEG_N) / LEG_N + radians(30);
    const span = TABLE_BOT - 0.5 - PLAT_Z;
    for (const [h0, h1] of [[0.28, 0.60]]){
      const p0: Vec3 = [(rb + (rt - rb) * h0) * cos(a), (rb + (rt - rb) * h0) * sin(a), PLAT_Z + span * h0];
      const p1: Vec3 = [(rb + (rt - rb) * h1) * cos(a2), (rb + (rt - rb) * h1) * sin(a2), PLAT_Z + span * h1];
      prism(mb, p0, p1, sec_tube(0.26, 10), { up: [0, 0, 1], mat: T_DARK, smooth: true });
      const p0b: Vec3 = [(rb + (rt - rb) * h1) * cos(a), (rb + (rt - rb) * h1) * sin(a), PLAT_Z + span * h1];
      const p1b: Vec3 = [(rb + (rt - rb) * h0) * cos(a2), (rb + (rt - rb) * h0) * sin(a2), PLAT_Z + span * h0];
      prism(mb, p0b, p1b, sec_tube(0.26, 10), { up: [0, 0, 1], mat: T_DARK, smooth: true });
    }
  }
  objs.push({ name: 'OLM_Table', mb, smooth: 32, slots });

  /* -------- booster quick disconnect -------- */
  mb = new MB();
  {
    const a = radians(200);
    const bx = 8.6 * cos(a), by = 8.6 * sin(a);
    prism(mb, [bx, by, PLAT_Z], [bx, by, DECK_Z - 1.2], sec_box(4.2, 3.4),
          { up: [cos(a), sin(a), 0], mat: T_DARK, smooth: false });
    prism(mb, [bx * 0.72, by * 0.72, DECK_Z - 2.4], [bx * 1.02, by * 1.02, DECK_Z - 1.6],
          sec_box(2.4, 2.0), { up: [0, 0, 1], mat: T_DKM, smooth: false });
  }
  objs.push({ name: 'OLM_BQD', mb, smooth: null, slots });

  /* -------- square launch platform -------- */
  mb = new MB();
  {
    const x0 = -38.0, x1 = 30.0, y0 = -31.0, y1 = 31.0, T = PLAT_Z;
    const i0 = mb.offset();
    for (const [x, y] of [[x1, y1], [x0, y1], [x0, y0], [x1, y0]]) mb.add_v([x, y, T]);
    mb.add_f([i0, i0+1, i0+2, i0+3], [[0,0],[9,0],[9,8],[0,8]], false, T_CONC);
    const j0 = mb.offset();
    for (const [x, y] of [[x1, y1], [x0, y1], [x0, y0], [x1, y0]]) mb.add_v([x, y, T - 2.4]);
    mb.add_f([j0+3, j0+2, j0+1, j0], [[0,0],[9,0],[9,8],[0,8]], false, T_CONCD);
    for (let k = 0; k < 4; k++){
      const k2 = (k + 1) % 4;
      mb.add_f([i0+k, i0+k2, j0+k2, j0+k], [[0,1],[6,1],[6,0],[0,0]], false, T_CONCD);
    }
    for (const [ax, ay, bx2, by2] of [[x1, y0, x1, y1], [x0, y1, x1, y1],
                                      [x0, y0, x0, y1], [x0, y0, x1, y0]])
      prism(mb, [ax, ay, T], [bx2, by2, T], sec_box(0.55, 1.05),
            { up: [0, 0, 1], mat: T_BLK, smooth: false, ext0: 0.28, ext1: 0.28 });
  }
  objs.push({ name: 'Pad_Platform', mb, smooth: null, slots });

  return objs;
}
