/**
 * Starship (the upper stage) — `ref_images/starship.html` §4, `ship.py`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * `raptor()` and `surface_patch()` are exported because booster.py calls both;
 * in the single-file demo they were simply in scope.
 */
import { MB, lathe, prism, ring_stack, sec_tube } from '../../procgen/sslib/meshbuilder'
import { PI, TAU, Vec, cos, radians, sin, sqrt, tan } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'

/** One flap's plan: hinge band, chord, sweep and thickness taper. */
export interface FlapSpec {
  z_bot: number
  z_top: number
  chord: number
  sweep_deg: number
  t_root: number
  t_tip: number
  phi_deg: number
  bot_sweep_deg: number
}

interface FlapBuildSpec extends FlapSpec {
  mat_top: number
  mat_bot: number
  mat_edge: number
  nspan?: number
  nchord?: number
}

export const SHIP: {
  R: number; SHIP_H: number; NOSE_L: number; BARREL_TOP: number; RING: number;
  SEG: number; NS_TPS: number; TPS_T: number; TPS_GAP: number;
  AFT_FLAP: FlapSpec; FWD_FLAP: FlapSpec;
} = {} as never;
SHIP.R = 4.5;
SHIP.SHIP_H = 50.3;
SHIP.NOSE_L = 12.70;
SHIP.BARREL_TOP = SHIP.SHIP_H - SHIP.NOSE_L;
SHIP.RING = 1.83;
SHIP.SEG = 192;
SHIP.NS_TPS = 136;
SHIP.TPS_T = 0.060;
SHIP.TPS_GAP = 0.014;
SHIP.AFT_FLAP = { z_bot: 1.05, z_top: 14.25, chord: 6.15, sweep_deg: 41.0, t_root: 0.72,
                  t_tip: 0.14, phi_deg: 0.0, bot_sweep_deg: 5.0 };
SHIP.FWD_FLAP = { z_bot: 37.30, z_top: 44.70, chord: 5.35, sweep_deg: 43.0, t_root: 0.62,
                  t_tip: 0.12, phi_deg: 0.0, bot_sweep_deg: 6.0 };
const OGIVE_MIX = 0.33;

function nose_pts(n = 96): Vec2[] {
  const Lz = SHIP.NOSE_L, Rr = SHIP.R, a = OGIVE_MIX;
  const rho = (Rr * Rr + Lz * Lz) / (2.0 * Rr);
  const pts: Vec2[] = [];
  for (let k = 0; k <= n; k++){
    const h = Lz * Math.pow(k / n, 0.94);
    const og = sqrt(Math.max(rho * rho - h * h, 0.0)) + Rr - rho;
    const cone = Rr * (1.0 - h / Lz);
    const t = Math.min(h / (Lz * 0.16), 1.0);
    const s = t * t * (3 - 2 * t);
    const y = og * (1.0 - (1.0 - a) * s) + cone * ((1.0 - a) * s);
    pts.push([Math.max(y, 0.0), h]);
  }
  while (pts.length > 3 && pts[pts.length - 1][0] < 0.26) pts.pop();
  const rt = pts[pts.length - 1][0], ht = pts[pts.length - 1][1];
  for (let k = 1; k <= 8; k++){
    const ang = (PI / 2) * k / 8;
    pts.push([rt * cos(ang), ht + rt * 1.15 * sin(ang)]);
  }
  return pts;
}

function ship_hull_profile(seams = true): Vec2[] {
  const R = SHIP.R, RING = SHIP.RING, BT = SHIP.BARREL_TOP;
  const lip = seams ? 0.0045 : 0.0;
  let p: Vec2[] = [[R - 0.12, 0.0], [R - 0.12, 0.06], [R, 0.17]];
  p = p.concat(ring_stack(0.17, BT, R, RING, lip, 0.013).slice(1));
  const npts = nose_pts();
  let acc = 0.0, last: Vec2 = npts[0];
  const out: Vec2[] = [];
  for (let i = 1; i < npts.length; i++){
    const r = npts[i][0], h = npts[i][1];
    acc += sqrt((r - last[0]) ** 2 + (h - last[1]) ** 2);
    if (seams && acc > RING && r > 0.6){ acc = 0.0; out.push([r + 0.004, h]); }
    out.push([r, h]);
    last = [r, h];
  }
  for (const [r, h] of out) p.push([r, BT + h]);
  return p;
}

let _SMOOTH: Vec2[] | null = null;
export function hull_r(z: number): number {
  if (_SMOOTH === null) _SMOOTH = ship_hull_profile(false);
  if (z <= SHIP.BARREL_TOP) return SHIP.R;
  for (let i = 0; i < _SMOOTH.length - 1; i++){
    const [r0, z0] = _SMOOTH[i], [r1, z1] = _SMOOTH[i + 1];
    if (z0 <= z && z <= z1 && z1 > z0) return r0 + (r1 - r0) * (z - z0) / (z1 - z0);
  }
  return Math.max(_SMOOTH[_SMOOTH.length - 1][0], 0.05);
}

function offset_profile(prof: Vec2[], d: number): Vec2[] {
  const n = prof.length, out: Vec2[] = [];
  for (let i = 0; i < n; i++){
    const i0 = Math.max(i - 1, 0), i1 = Math.min(i + 1, n - 1);
    const dr = prof[i1][0] - prof[i0][0];
    const dz = prof[i1][1] - prof[i0][1];
    const m = sqrt(dr * dr + dz * dz) || 1.0;
    out.push([prof[i][0] + (dz / m) * d, prof[i][1] - (dr / m) * d]);
  }
  return out;
}

function tps_shell(
  mb: MB, prof0: Vec2[], half_fn: (k: number, r: number, z: number) => number,
  thick: number, mat_out: number, mat_side: number, jitter: number,
  ns = SHIP.NS_TPS, gap = SHIP.TPS_GAP,
): void {
  let outer = offset_profile(prof0, thick);
  let inner = offset_profile(prof0, gap);
  const n = prof0.length;
  outer = outer.map((p, k) => [Math.max(p[0], prof0[k][0] + thick * 0.72), p[1]]);
  inner = inner.map((p, k) => [Math.max(p[0], prof0[k][0] + gap * 0.72), p[1]]);
  const prof = inner;
  const halves: number[] = [];
  for (let k = 0; k < n; k++){
    let h = half_fn(k, prof[k][0], prof[k][1]);
    if (jitter) h += jitter * ((((k * 1367 + 41) % 97) / 97.0) - 0.5);
    halves.push(Math.min(h, radians(178.5)));
  }
  const vlen: number[] = [0.0];
  for (let k = 1; k < n; k++)
    vlen.push(vlen[k-1] + sqrt((prof[k][0]-prof[k-1][0])**2 + (prof[k][1]-prof[k-1][1])**2));
  const O: number[][] = [], I: number[][] = [];
  for (let k = 0; k < n; k++){
    const h = halves[k];
    const ro = outer[k][0], zo = outer[k][1];
    const ri = prof[k][0], zi = prof[k][1];
    const rowO: number[] = [], rowI: number[] = [];
    for (let s = 0; s <= ns; s++){
      const a = -h + 2 * h * s / ns;
      rowO.push(mb.add_v([ro * sin(a), -ro * cos(a), zo]));
      rowI.push(mb.add_v([ri * sin(a), -ri * cos(a), zi]));
    }
    O.push(rowO); I.push(rowI);
  }
  for (let k = 0; k < n - 1; k++){
    const r0 = outer[k][0], r1 = outer[k+1][0];
    const h0 = halves[k], h1 = halves[k+1];
    for (let s = 0; s < ns; s++){
      const A = O[k][s], B = O[k][s+1], C = O[k+1][s+1], D = O[k+1][s];
      const u0 = (-h0 + 2 * h0 * s / ns) * r0;
      const u1 = (-h0 + 2 * h0 * (s + 1) / ns) * r0;
      const u2 = (-h1 + 2 * h1 * (s + 1) / ns) * r1;
      const u3 = (-h1 + 2 * h1 * s / ns) * r1;
      mb.add_f([A, B, C, D],
               [[u0, vlen[k]], [u1, vlen[k]], [u2, vlen[k+1]], [u3, vlen[k+1]]], true, mat_out);
      mb.add_f([I[k+1][s], I[k+1][s+1], I[k][s+1], I[k][s]],
               [[u3, vlen[k+1]], [u2, vlen[k+1]], [u1, vlen[k]], [u0, vlen[k]]], true, mat_side);
    }
  }
  for (let k = 0; k < n - 1; k++){
    for (const [side, flip] of [[0, false], [ns, true]] as Array<[number, boolean]>){
      const q = [O[k][side], O[k+1][side], I[k+1][side], I[k][side]];
      mb.add_f(flip ? q : q.slice().reverse(),
               [[0, vlen[k]], [0, vlen[k+1]], [.03, vlen[k+1]], [.03, vlen[k]]], false, mat_side);
    }
  }
  for (const [k, rev] of [[0, true], [n - 1, false]] as Array<[number, boolean]>){
    for (let s = 0; s < ns; s++){
      const q = [O[k][s], O[k][s+1], I[k][s+1], I[k][s]];
      mb.add_f(rev ? q : q.slice().reverse(), [[0,0],[.02,0],[.02,.03],[0,.03]], false, mat_side);
    }
  }
}

function flap_solid(mb: MB, hinge_r: ((z: number) => number) | number, az: number, p: FlapBuildSpec): void {
  const { z_bot, z_top, chord, sweep_deg, t_root, t_tip, phi_deg, bot_sweep_deg,
          mat_top, mat_bot, mat_edge } = p;
  const nspan = p.nspan !== undefined ? p.nspan : 28;
  const nchord = p.nchord !== undefined ? p.nchord : 20;
  const sgn = az >= 0 ? 1.0 : -1.0;
  const a = radians(az);
  const rad = new Vec(sin(a), -cos(a), 0.0);
  const tan_lee = new Vec(cos(a) * sgn, sin(a) * sgn, 0.0);
  const up = new Vec(0, 0, 1);
  const phi = radians(phi_deg);
  const cdir = rad.mul(cos(phi)).add(tan_lee.mul(sin(phi))).normalized();
  let ndir = cdir.cross(up).normalized();
  if (ndir.dot(tan_lee.neg()) < 0) ndir = ndir.neg();
  const hr: (z: number) => number = (typeof hinge_r === 'function') ? hinge_r : (() => hinge_r);
  const swp = tan(radians(sweep_deg)), bswp = tan(radians(bot_sweep_deg));
  const zt = (u: number): number => z_top - u * chord * swp;
  const zb = (u: number): number => z_bot + u * chord * bswp;
  const half_t = (u: number): number => {
    let base = 0.5 * (t_root + (t_tip - t_root) * u);
    if (u > 0.90){ const k = (u - 0.90) / 0.10; base *= sqrt(Math.max(1.0 - k * k, 0.0)); }
    return Math.max(base, 0.004);
  };
  const top: number[][] = [], bot: number[][] = [];
  for (let i = 0; i <= nchord; i++){
    const u = i / nchord;
    const rowT: number[] = [], rowB: number[] = [];
    for (let j = 0; j <= nspan; j++){
      const v = j / nspan;
      const z = zb(u) + (zt(u) - zb(u)) * v;
      const base = rad.mul(hr(z)).add(cdir.mul(u * chord)).add(up.mul(z));
      const ht = half_t(u);
      const e = Math.min(v, 1 - v) * 2.0;
      let ef = e < 0.020 ? sqrt(Math.max(1.0 - (1.0 - Math.min(e / 0.020, 1.0)) ** 2, 0.0)) : 1.0;
      ef = Math.max(ef, 0.04);
      rowT.push(mb.add_v(base.add(ndir.mul(ht * ef))));
      rowB.push(mb.add_v(base.sub(ndir.mul(ht * ef))));
    }
    top.push(rowT); bot.push(rowB);
  }
  const quad = (rows: number[][], i: number, j: number, flip: boolean, mat: number): void => {
    const A = rows[i][j], B = rows[i+1][j], C = rows[i+1][j+1], D = rows[i][j+1];
    const uu = (i / nchord) * chord, uu2 = ((i + 1) / nchord) * chord;
    const vv = (j / nspan) * (z_top - z_bot), vv2 = ((j + 1) / nspan) * (z_top - z_bot);
    const uvq: Vec2[] = [[uu, vv], [uu2, vv], [uu2, vv2], [uu, vv2]];
    if (flip) mb.add_f([D, C, B, A], uvq.slice().reverse(), true, mat);
    else mb.add_f([A, B, C, D], uvq, true, mat);
  };
  for (let i = 0; i < nchord; i++)
    for (let j = 0; j < nspan; j++){ quad(top, i, j, false, mat_top); quad(bot, i, j, true, mat_bot); }
  const i = nchord;
  for (let j = 0; j < nspan; j++)
    mb.add_f([top[i][j], bot[i][j], bot[i][j+1], top[i][j+1]],
             [[0,0],[.1,0],[.1,.1],[0,.1]], true, mat_edge);
  for (const [j, flip] of [[0, true], [nspan, false]] as Array<[number, boolean]>){
    for (let k = 0; k < nchord; k++){
      const q = [top[k][j], top[k+1][j], bot[k+1][j], bot[k][j]];
      mb.add_f(flip ? q : q.slice().reverse(), [[0,0],[.1,0],[.1,.1],[0,.1]], true, mat_edge);
    }
  }
  for (let j = 0; j < nspan; j++)
    mb.add_f([top[0][j+1], bot[0][j+1], bot[0][j], top[0][j]],
             [[0,0],[.1,0],[.1,.1],[0,.1]], false, mat_edge);
}

function hinge_fairing(mb: MB, az: number, z0: number, z1: number, r_fn: ((z: number) => number) | number, rt: number, mat: number, seg = 26, nz = 22): void {
  const a = radians(az);
  const rad = new Vec(sin(a), -cos(a), 0.0);
  const up = new Vec(0, 0, 1);
  const side = new Vec(-rad.y, rad.x, 0.0);
  const idx: number[][] = [];
  for (let i = 0; i <= nz; i++){
    const t = i / nz;
    const z = z0 + (z1 - z0) * t;
    const rr = (typeof r_fn === 'function') ? r_fn(z) : r_fn;
    const e = Math.min(t, 1 - t) * (z1 - z0);
    const cap = e >= rt ? 1.0 : sqrt(Math.max(1.0 - (1.0 - e / rt) ** 2, 0.03));
    const c = rad.mul(rr).add(up.mul(z));
    const row: number[] = [];
    for (let k = 0; k < seg; k++){
      const ang = TAU * k / seg;
      row.push(mb.add_v(c.add(rad.mul(rt * cap * cos(ang))).add(side.mul(rt * cap * sin(ang)))));
    }
    idx.push(row);
  }
  for (let i = 0; i < idx.length - 1; i++)
    for (let k = 0; k < seg; k++){
      const k2 = (k + 1) % seg;
      mb.add_f([idx[i][k], idx[i][k2], idx[i+1][k2], idx[i+1][k]],
               [[0,0],[1,0],[1,1],[0,1]], true, mat);
    }
  mb.add_f(idx[0].slice().reverse(), null, false, mat);
  mb.add_f(idx[idx.length - 1].slice(), null, false, mat);
}

export function raptor(mb: MB, x: number, y: number, z: number, exit_r: number, len: number, mat_body: number, mat_noz: number, seg = 32, vac = false): void {
  const throat_r = exit_r * (vac ? 0.235 : 0.34);
  const z_exit = z - len * 0.80;
  const z_thr = z - len * 0.235;
  const prof: Vec2[] = [];
  const n = 24;
  for (let k = 0; k <= n; k++){
    const t = k / n;
    const zz = z_exit + (z_thr - z_exit) * t;
    const s = 1.0 - t;
    prof.push([throat_r + (exit_r - throat_r) * Math.pow(s, 0.58), zz]);
  }
  prof.push([throat_r * 1.30, z_thr + 0.045 * len]);
  prof.push([throat_r * 2.00, z_thr + 0.105 * len]);
  prof.push([throat_r * 2.10, z_thr + 0.175 * len]);
  prof.push([throat_r * 2.10, z - 0.012 * len]);
  lathe(mb, prof, seg, { mat: mat_noz, center: [x, y], smooth: true, cap_top: true });
  const lip: Vec2[] = [[exit_r, z_exit], [exit_r * 1.030, z_exit + exit_r * 0.055],
               [exit_r * 1.030, z_exit + exit_r * 0.115], [exit_r * 0.982, z_exit + exit_r * 0.150]];
  lathe(mb, lip, seg, { mat: mat_body, center: [x, y], smooth: true });
  const ph: Vec2[] = [[throat_r * 2.10, z - 0.010 * len], [throat_r * 2.55, z + 0.030 * len],
              [throat_r * 2.55, z + 0.095 * len]];
  lathe(mb, ph, Math.max(16, Math.floor(seg / 2)), { mat: mat_body, center: [x, y], smooth: true, cap_top: true });
  for (let k = 0; k < 2; k++){
    const aa = k * PI + 0.7;
    const px = x + throat_r * 2.35 * cos(aa), py = y + throat_r * 2.35 * sin(aa);
    prism(mb, [px, py, z + 0.004 * len], [px, py, z + 0.082 * len],
          sec_tube(throat_r * 0.80, 12), { up: [0, 0, 1], mat: mat_body, smooth: true });
  }
}

const hull_pt = (a: number, r: number, z: number): Vec3 => [r * sin(a), -r * cos(a), z];

export function surface_patch(mb: MB, a_c: number, z_c: number, w: number, h: number, r: number, bulge: number, mat: number, na = 8, nz = 1, smooth = true): void {
  nz = 1;
  const dw = w / r;
  const top: number[][] = [], base: number[][] = [];
  for (let j = 0; j <= nz; j++){
    const z = z_c - h / 2 + h * j / nz;
    const rt: number[] = [], rb: number[] = [];
    for (let k = 0; k <= na; k++){
      const a = a_c - dw / 2 + dw * k / na;
      rt.push(mb.add_v(hull_pt(a, r + bulge, z)));
      rb.push(mb.add_v(hull_pt(a, r + 0.004, z)));
    }
    top.push(rt); base.push(rb);
  }
  for (let j = 0; j < nz; j++)
    for (let k = 0; k < na; k++)
      mb.add_f([top[j][k], top[j][k+1], top[j+1][k+1], top[j+1][k]],
               [[0,0],[1,0],[1,1],[0,1]], smooth, mat);
  for (let k = 0; k < na; k++){
    mb.add_f([top[0][k+1], top[0][k], base[0][k], base[0][k+1]], [[0,0],[1,0],[1,.1],[0,.1]], false, mat);
    mb.add_f([top[nz][k], top[nz][k+1], base[nz][k+1], base[nz][k]], [[0,0],[1,0],[1,.1],[0,.1]], false, mat);
  }
  for (let j = 0; j < nz; j++){
    mb.add_f([top[j][0], top[j+1][0], base[j+1][0], base[j][0]], [[0,0],[1,0],[1,.1],[0,.1]], false, mat);
    mb.add_f([top[j+1][na], top[j][na], base[j][na], base[j+1][na]], [[0,0],[1,0],[1,.1],[0,.1]], false, mat);
  }
  const ring = base[0].concat(base[nz].slice().reverse());
  const ruv: Vec2[] = [];
  for (let i = 0; i <= na; i++) ruv.push([i / na, 0.0]);
  for (let i = na; i >= 0; i--) ruv.push([i / na, 1.0]);
  mb.add_f(ring, ruv, false, mat);
}

export function shipBuild(): BuildObject[] {
  const S_STEEL = 0, S_TILE = 1, S_BLACK = 3, S_ENG = 4, S_NOZ = 5, S_DKM = 6, S_DIRTY = 7;  /* slot 2 (tiles_nose) is in the list below but no face uses it */
  const slots = ['steel_ship', 'tiles', 'tiles_nose', 'black', 'engine', 'engine_hot', 'dark_metal', 'steel_dirty'];
  const R = SHIP.R, BT = SHIP.BARREL_TOP, SEG = SHIP.SEG;
  const prof = ship_hull_profile(true);
  const objs: BuildObject[] = [];
  let mb: MB;

  /* hull */
  mb = new MB();
  lathe(mb, prof, SEG, { mat: S_STEEL, smooth: true, tile_w: 0.205 });
  lathe(mb, [[R - 0.12, 0.0], [R - 0.34, 0.02], [R - 0.34, 1.9]], SEG, { mat: S_DIRTY, smooth: true });
  objs.push({ name: 'Ship_Hull', mb, smooth: 18, slots });

  /* TPS tile shell */
  const half_fn = (_k: number, _r: number, z: number): number => {
    if (z <= BT) return radians(104.0);
    const t = (z - BT) / SHIP.NOSE_L;
    return radians(104.0 + 74.0 * Math.min(1.0, Math.pow(t / 0.60, 0.85)));
  };
  mb = new MB();
  const sm = ship_hull_profile(false);
  let i_start = 0;
  for (let i = 0; i < sm.length; i++){ if (sm[i][1] >= 1.30){ i_start = i; break; } }
  tps_shell(mb, sm.slice(i_start), half_fn, SHIP.TPS_T, S_TILE, S_BLACK, radians(1.7));
  objs.push({ name: 'Ship_TPS', mb, smooth: 34, slots });

  /* flaps */
  mb = new MB();
  const AFT_AZ = 90.0, FWD_AZ = 90.0;
  const hr = (z: number): number => hull_r(z) + 0.10;
  for (const s of [1, -1]){
    flap_solid(mb, hr, s * AFT_AZ, Object.assign({}, SHIP.AFT_FLAP,
      { mat_top: S_TILE, mat_bot: S_STEEL, mat_edge: S_BLACK }));
    flap_solid(mb, hr, s * FWD_AZ, Object.assign({}, SHIP.FWD_FLAP,
      { mat_top: S_TILE, mat_bot: S_STEEL, mat_edge: S_BLACK }));
    hinge_fairing(mb, s * AFT_AZ, SHIP.AFT_FLAP.z_bot - 0.42, SHIP.AFT_FLAP.z_top + 0.34, hr, 0.58, S_BLACK);
    hinge_fairing(mb, s * FWD_AZ, SHIP.FWD_FLAP.z_bot - 0.36, SHIP.FWD_FLAP.z_top + 0.28, hr, 0.50, S_BLACK);
  }
  objs.push({ name: 'Ship_Flaps', mb, smooth: 36, slots });

  /* engines */
  mb = new MB();
  const zb = 3.45;
  for (let k = 0; k < 3; k++){
    const a = TAU * k / 3 + radians(60);
    raptor(mb, 0.95 * cos(a), 0.95 * sin(a), zb, 0.65, 3.10, S_ENG, S_NOZ);
  }
  for (let k = 0; k < 3; k++){
    const a = TAU * k / 3;
    raptor(mb, 2.64 * cos(a), 2.64 * sin(a), zb + 0.30, 1.20, 4.60, S_ENG, S_NOZ, 32, true);
  }
  lathe(mb, [[0.0, zb + 1.05], [4.14, zb + 1.05], [4.14, zb + 1.30]], 64, { mat: S_DKM, smooth: false });
  objs.push({ name: 'Ship_Engines', mb, smooth: 30, slots });

  /* surface details */
  mb = new MB();
  for (const [a0, w, z0, z1, bul] of [[radians(180.0), 0.62, 1.9, 36.4, 0.19],
                                      [radians(166.0), 0.34, 2.4, 34.6, 0.11]]){
    const n = 10, rows: number[][] = [];
    for (const z of [z0, z1]){
      const row: number[] = [];
      for (let k = 0; k <= n; k++){
        const aa = a0 - (w / R) / 2 + (w / R) * k / n;
        const b = bul * sqrt(Math.max(0.0, 1 - (2 * k / n - 1) ** 2));
        row.push(mb.add_v(hull_pt(aa, R + 0.012 + b, z)));
      }
      rows.push(row);
    }
    for (let k = 0; k < n; k++)
      mb.add_f([rows[0][k], rows[0][k+1], rows[1][k+1], rows[1][k]],
               [[0,0],[.2,0],[.2,1],[0,1]], true, S_STEEL);
    mb.add_f(rows[0].slice().reverse(), null, false, S_STEEL);
    mb.add_f(rows[1].slice(), null, false, S_STEEL);
  }
  for (const [aa, zz, w, h] of [[150, 8.0, 1.15, 1.55], [212, 12.5, 1.0, 1.4],
                                [196, 30.5, 0.85, 1.05], [164, 17.4, 0.8, 1.0]])
    surface_patch(mb, radians(aa), zz, w, h, R, 0.038, S_DKM);
  for (const aa of [150, 210])
    surface_patch(mb, radians(aa), 43.0, 0.55, 0.42, hull_r(43.0), 0.030, S_DKM, 5, 1);
  objs.push({ name: 'Ship_Details', mb, smooth: 34, slots });

  return objs;
}
