/**
 * The OLIT (tower, chopsticks, QD arm) — `ref_images/starship.html` §6,
 * `tower.py`. GENERATED by tools/starship-gen.mjs; edit the generator.
 *
 * `TW` is MUTATED by the assembly before `towerBuild()` runs: the catch arms'
 * height and the vehicle's X both fall out of where the ship's forward flap
 * ends up. `starshipAssemble.ts` owns that order; nothing else may write TW.
 */
import { MB, prism, sec_box, sec_i, sec_tube } from '../../procgen/sslib/meshbuilder'
import { V, Vec, cos, radians, sin, sqrt } from '../../procgen/sslib/mathkit'
import type { Pt3, Vec2 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'

/**
 * The literal's own fields plus the five the source derives from them on the
 * lines that follow, plus the two the assembly writes back. CHORD is a 4-tuple
 * because the source spreads it into `sec_i(w, h, tw, tf)`.
 */
interface TowerConfig {
  W: number
  SEC_H: number
  N_SEC: number
  BASE_Z: number
  BAYS: number
  COL: number
  MIDP: number
  CHORD: [number, number, number, number]
  DIAG_W: number
  DIAG_T: number
  ARM_Z: number
  ARM_LEN: number
  ARM_SPLAY: number
  ARM_PIVOT_Y: number
  ARM_D_ROOT: number
  ARM_D_TIP: number
  ARM_W_ROOT: number
  ARM_W_TIP: number
  QD_Z: number
  TOWER_X: number
  PAD_TS: number[]
  PAD_L: number
  PAD_H: number
  PAD_DZ: number
  PAD_SEAT: number
  VEHICLE_X: number
  HW: number
  TRUSS_TOP: number
  CROWN_TOP: number
  ROD_TOP: number
  BAY_H: number
}

export const TW = {
  W: 12.20, SEC_H: 14.60, N_SEC: 9, BASE_Z: 2.00, BAYS: 4,
  COL: 1.18, MIDP: 0.46, CHORD: [0.86, 1.00, 0.11, 0.14],
  DIAG_W: 0.52, DIAG_T: 0.30,
  ARM_Z: 126.0, ARM_LEN: 26.5, ARM_SPLAY: 10.0, ARM_PIVOT_Y: 5.60,
  ARM_D_ROOT: 5.10, ARM_D_TIP: 2.65, ARM_W_ROOT: 3.45, ARM_W_TIP: 2.45,
  QD_Z: 94.6, TOWER_X: -17.50, PAD_TS: [0.40, 0.60], PAD_L: 1.55, PAD_H: 0.85,
  PAD_DZ: 0.28, PAD_SEAT: 0.60, VEHICLE_X: 0.0
} as TowerConfig;
TW.HW = TW.W / 2;
TW.TRUSS_TOP = TW.BASE_Z + TW.SEC_H * TW.N_SEC;
TW.CROWN_TOP = TW.TRUSS_TOP + 6.10;
TW.ROD_TOP = 146.0;
TW.BAY_H = TW.SEC_H / TW.BAYS;

export function pad_geom(t = TW.PAD_SEAT, sgn = 1): [number, number, number, number] {
  const px = TW.TOWER_X + TW.HW + 1.1;
  const a = radians(sgn * TW.ARM_SPLAY);
  const dist = TW.ARM_LEN * t;
  const x = px + dist * cos(a);
  const y = sgn * TW.ARM_PIVOT_Y + dist * sin(a);
  const d = TW.ARM_D_ROOT + (TW.ARM_D_TIP - TW.ARM_D_ROOT) * t;
  const top_chord = d * (1.0 - 0.72);
  return [x, y, top_chord + TW.PAD_DZ + TW.PAD_H / 2, top_chord + 0.22];
}

const corners = (): Vec2[] => { const H = TW.HW; return [[H, H], [-H, H], [-H, -H], [H, -H]]; };
function faces(): Array<[Vec2, Vec2, Vec]> {
  const c = corners(), out: Array<[Vec2, Vec2, Vec]> = [];
  for (let i = 0; i < 4; i++){
    const a = c[i], b = c[(i + 1) % 4];
    const n = new Vec((a[0] + b[0]) / 2, (a[1] + b[1]) / 2, 0).normalized();
    out.push([a, b, n]);
  }
  return out;
}

export function railing(mb: MB, pts: Vec2[], z: number, h: number, mat: number, post_every = 2.2): void {
  const n = pts.length;
  for (let i = 0; i < n; i++){
    const a = new Vec(pts[i][0], pts[i][1], z);
    const b = new Vec(pts[(i + 1) % n][0], pts[(i + 1) % n][1], z);
    const d = b.sub(a);
    const ln = d.length;
    if (ln < 1e-6) continue;
    const u = d.mul(1 / ln);
    const side = new Vec(-u.y, u.x, 0);
    for (const hh of [h, h * 0.55])
      prism(mb, a.add(new Vec(0, 0, hh)), b.add(new Vec(0, 0, hh)), sec_box(0.07, 0.07),
            { up: [0, 0, 1], mat, smooth: false });
    const m = Math.max(1, Math.trunc(ln / post_every));
    for (let k = 0; k <= m; k++){
      const p = a.add(u.mul(ln * k / m));
      prism(mb, p, p.add(new Vec(0, 0, h)), sec_box(0.07, 0.07), { up: side, mat, smooth: false });
    }
  }
}

function build_truss(mb: MB, m_col: number, m_beam: number, m_diag: number, m_grate: number): void {
  const c = corners(), COL = TW.COL, HW = TW.HW, BASE_Z = TW.BASE_Z, TRUSS_TOP = TW.TRUSS_TOP;
  for (const [x, y] of c)
    prism(mb, [x, y, BASE_Z - 0.6], [x, y, TRUSS_TOP], sec_box(COL, COL),
          { up: [0, 1, 0], mat: m_col, smooth: false });
  const nlev = TW.N_SEC * TW.BAYS;
  for (let lv = 0; lv <= nlev; lv++){
    const z = BASE_Z + lv * TW.BAY_H;
    for (const [a, b] of faces())
      prism(mb, [a[0], a[1], z], [b[0], b[1], z], sec_i(...TW.CHORD),
            { up: [0, 0, 1], mat: m_beam, smooth: false, ext0: -COL / 2, ext1: -COL / 2 });
    if (lv % TW.BAYS === 0){
      prism(mb, [c[0][0], c[0][1], z], [c[2][0], c[2][1], z], sec_i(0.60, 0.78, 0.09, 0.11),
            { up: [0, 0, 1], mat: m_beam, smooth: false, ext0: -COL / 2, ext1: -COL / 2 });
      prism(mb, [c[1][0], c[1][1], z], [c[3][0], c[3][1], z], sec_i(0.60, 0.78, 0.09, 0.11),
            { up: [0, 0, 1], mat: m_beam, smooth: false, ext0: -COL / 2, ext1: -COL / 2 });
    }
  }
  for (const [a, b, n] of faces()){
    const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2;
    prism(mb, [mx, my, BASE_Z], [mx, my, TRUSS_TOP], sec_box(TW.MIDP, TW.MIDP),
          { up: [n.x, n.y, 0], mat: m_col, smooth: false });
  }
  for (let lv = 0; lv < nlev; lv++){
    const z0 = BASE_Z + lv * TW.BAY_H + 0.50;
    const z1 = BASE_Z + (lv + 1) * TW.BAY_H - 0.50;
    for (const [a, b, n] of faces()){
      const ax = a[0] - n.x * 0.05, ay = a[1] - n.y * 0.05;
      const bx = b[0] - n.x * 0.05, by = b[1] - n.y * 0.05;
      let ux = bx - ax, uy = by - ay;
      const ln = sqrt(ux * ux + uy * uy);
      ux /= ln; uy /= ln;
      const ins = COL * 0.44, mid = TW.MIDP * 0.55;
      for (const [s0, s1] of [[ins, ln / 2 - mid], [ln / 2 + mid, ln - ins]]){
        const q0 = [ax + ux * s0, ay + uy * s0, z0];
        const q1 = [ax + ux * s1, ay + uy * s1, z1];
        const q2 = [ax + ux * s1, ay + uy * s1, z0];
        const q3 = [ax + ux * s0, ay + uy * s0, z1];
        prism(mb, q0, q1, sec_box(TW.DIAG_W, TW.DIAG_T), { up: [n.x, n.y, 0], mat: m_diag, smooth: false });
        prism(mb, q2, q3, sec_box(TW.DIAG_W, TW.DIAG_T), { up: [n.x, n.y, 0], mat: m_diag, smooth: false });
      }
    }
  }
  for (let s = 0; s < TW.N_SEC; s++){
    const z = BASE_Z + s * TW.SEC_H;
    const k = HW - COL * 0.62;
    if (s % 2 === 0){
      const i0 = mb.offset();
      for (const [x, y] of [[k, k], [-k, k], [-k, -k], [k, -k]]) mb.add_v([x, y, z + 0.04]);
      mb.add_f([i0, i0+1, i0+2, i0+3], [[0,0],[4,0],[4,4],[0,4]], false, m_grate);
      mb.add_f([i0+3, i0+2, i0+1, i0], [[0,0],[4,0],[4,4],[0,4]], false, m_grate);
    }
    for (let f = 0; f < 4; f++){
      const zz0 = z + f * (TW.SEC_H / 4);
      const zz1 = zz0 + TW.SEC_H / 4;
      const sgn = f % 2 === 0 ? 1 : -1;
      prism(mb, [-k + 0.9, sgn * (k - 1.1), zz0], [k - 2.6, -sgn * (k - 1.1), zz1],
            sec_box(1.25, 0.16), { up: [0, 0, 1], mat: m_grate, smooth: false });
    }
  }
  for (let lv = 0; lv < nlev; lv += 2){
    const z = BASE_Z + lv * TW.BAY_H;
    const k = HW - COL * 0.62;
    const i0 = mb.offset();
    for (const [x, y] of [[k, k - 3.2], [k - 3.6, k - 3.2], [k - 3.6, k], [k, k]])
      mb.add_v([x, y, z + 0.03]);
    mb.add_f([i0, i0+1, i0+2, i0+3], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
    mb.add_f([i0+3, i0+2, i0+1, i0], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
  }
  const runs = [[HW - 1.9, -HW + 1.9], [-HW + 1.9, HW - 1.9], [-HW + 2.0, -HW + 2.0]];
  for (const [cx, cy] of runs)
    for (const [dx, dy, rr, top] of [[0.0, 0.0, 0.34, 12.0], [0.85, 0.15, 0.24, 30.0],
                                     [0.20, 0.90, 0.20, 8.0], [0.75, 0.85, 0.16, 46.0]])
      prism(mb, [cx + dx, cy + dy, BASE_Z], [cx + dx, cy + dy, TRUSS_TOP - top],
            sec_tube(rr, 8), { up: [0, 0, 1], mat: m_diag, smooth: true });
  for (let lv = 0; lv < nlev; lv += 3){
    const z = BASE_Z + lv * TW.BAY_H + TW.BAY_H * 0.5;
    for (const [cx, cy] of runs)
      prism(mb, [cx - 0.4, cy - 0.4, z], [cx + 1.2, cy + 1.2, z], sec_box(0.30, 0.22),
            { up: [0, 0, 1], mat: m_beam, smooth: false });
  }
}

function build_rails(mb: MB, m_col: number, m_beam: number, m_dark: number, face_x = 1): void {
  const xf = TW.HW * face_x, BASE_Z = TW.BASE_Z, TRUSS_TOP = TW.TRUSS_TOP;
  for (const y of [3.35, -3.35]){
    prism(mb, [xf + 0.55, y, BASE_Z], [xf + 0.55, y, TRUSS_TOP - 1.0], sec_box(1.10, 1.35),
          { up: [0, 1, 0], mat: m_col, smooth: false });
    const nst = Math.trunc((TRUSS_TOP - BASE_Z) / 4.0);
    for (let k = 0; k < nst; k++){
      const z = BASE_Z + 2.0 + k * 4.0;
      prism(mb, [xf - 0.1, y, z], [xf + 1.1, y, z], sec_box(0.55, 0.30),
            { up: [0, 0, 1], mat: m_beam, smooth: false });
    }
  }
  const ex = -TW.HW + 1.35;
  for (const y of [-1.55, 1.55])
    prism(mb, [ex, y, BASE_Z], [ex, y, TRUSS_TOP - 4.0], sec_box(0.34, 0.34),
          { up: [1, 0, 0], mat: m_col, smooth: false });
  prism(mb, [ex + 0.55, 0.0, 46.0], [ex + 0.55, 0.0, 49.4], sec_box(2.10, 2.90),
        { up: [0, 1, 0], mat: m_dark, smooth: false });
}

function build_crown(mb: MB, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number): void {
  const c = corners(), COL = TW.COL, HW = TW.HW;
  const z0 = TW.TRUSS_TOP, z1 = TW.CROWN_TOP;
  for (const [x, y] of c)
    prism(mb, [x, y, z0 - 0.2], [x, y, z1], sec_box(COL * 0.94, COL * 0.94),
          { up: [0, 1, 0], mat: m_col, smooth: false });
  const lvls = [z0, z0 + (z1 - z0) * 0.5, z1];
  for (const zz of lvls){
    for (const [a, b] of faces())
      prism(mb, [a[0], a[1], zz], [b[0], b[1], zz], sec_i(0.74, 0.90, 0.09, 0.12),
            { up: [0, 0, 1], mat: m_beam, smooth: false, ext0: -COL / 2, ext1: -COL / 2 });
    prism(mb, [c[0][0], c[0][1], zz], [c[2][0], c[2][1], zz], sec_i(0.56, 0.72, 0.09, 0.11),
          { up: [0, 0, 1], mat: m_beam, smooth: false, ext0: -COL / 2, ext1: -COL / 2 });
  }
  for (let i = 0; i < 2; i++){
    const za = lvls[i] + 0.5, zbb = lvls[i + 1] - 0.5;
    for (const [a, b, n] of faces()){
      let ux = b[0] - a[0], uy = b[1] - a[1];
      const ln = sqrt(ux * ux + uy * uy); ux /= ln; uy /= ln;
      const ins = 0.45;
      prism(mb, [a[0] + ux * ins, a[1] + uy * ins, za], [b[0] - ux * ins, b[1] - uy * ins, zbb],
            sec_box(TW.DIAG_W, TW.DIAG_T), { up: [n.x, n.y, 0], mat: m_diag, smooth: false });
      prism(mb, [b[0] - ux * ins, b[1] - uy * ins, za], [a[0] + ux * ins, a[1] + uy * ins, zbb],
            sec_box(TW.DIAG_W, TW.DIAG_T), { up: [n.x, n.y, 0], mat: m_diag, smooth: false });
    }
  }
  for (const zz of [lvls[1], z1]){
    const i0 = mb.offset();
    const kk = HW - COL * 0.55;
    for (const [x, y] of [[kk, kk], [-kk, kk], [-kk, -kk], [kk, -kk]]) mb.add_v([x, y, zz + 0.52]);
    mb.add_f([i0, i0+1, i0+2, i0+3], [[0,0],[4,0],[4,4],[0,4]], false, m_grate);
    mb.add_f([i0+3, i0+2, i0+1, i0], [[0,0],[4,0],[4,4],[0,4]], false, m_grate);
    railing(mb, [[kk, kk], [-kk, kk], [-kk, -kk], [kk, -kk]], zz + 0.54, 1.15, m_beam);
  }
  const px = HW + 2.9;
  const i0 = mb.offset();
  for (const [x, y] of [[px, 4.2], [HW, 4.2], [HW, -4.2], [px, -4.2]]) mb.add_v([x, y, z1 + 0.52]);
  mb.add_f([i0, i0+1, i0+2, i0+3], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
  mb.add_f([i0+3, i0+2, i0+1, i0], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
  railing(mb, [[px, 4.2], [px, -4.2]], z1 + 0.54, 1.1, m_beam);
  for (const y of [4.2, -4.2])
    prism(mb, [HW, y, z1 - 2.6], [px, y, z1 + 0.5], sec_box(0.34, 0.38),
          { up: [0, 1, 0], mat: m_col, smooth: false });
  for (const [mx, my] of [[HW - 1.1, HW - 1.1], [-HW + 1.1, -HW + 1.1]])
    prism(mb, [mx, my, z1], [mx, my, TW.ROD_TOP], sec_tube(0.26, 8),
          { up: [0, 0, 1], mat: m_col, smooth: true, scale1: 0.30 });
  for (const [bx, by, bw, bd, bh] of [[2.4, -3.4, 3.4, 2.6, 2.3], [-3.4, 2.6, 2.6, 2.2, 1.7],
                                      [-3.0, -3.4, 2.0, 2.0, 1.2]])
    prism(mb, [bx, by, z1 + 0.54], [bx, by, z1 + 0.54 + bh], sec_box(bw, bd),
          { up: [0, 1, 0], mat: m_dark, smooth: false });
}

function chopstick(mb: MB, pivot: Pt3, yaw_deg: number, len: number, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number): void {
  const d_root = TW.ARM_D_ROOT, d_tip = TW.ARM_D_TIP, w_root = TW.ARM_W_ROOT, w_tip = TW.ARM_W_TIP;
  const o = V(pivot);
  const a = radians(yaw_deg);
  const f = new Vec(cos(a), sin(a), 0.0);
  const s = new Vec(-sin(a), cos(a), 0.0);
  const u = new Vec(0, 0, 1.0);
  const P = (t: number, sw: number, du: number): Vec => {
    const d = d_root + (d_tip - d_root) * t;
    const w = w_root + (w_tip - w_root) * t;
    return o.add(f.mul(len * t)).add(s.mul(sw * w / 2)).add(u.mul(du * d - d * 0.72));
  };
  const NB_ = 9;
  for (const sw of [-1, 1])
    for (const du of [0, 1]){
      const pts: Vec[] = [];
      for (let i = 0; i <= NB_; i++) pts.push(P(i / NB_, sw, du));
      for (let i = 0; i < NB_; i++){
        const sec = du ? sec_box(0.52, 0.62) : sec_box(0.42, 0.48);
        prism(mb, pts[i], pts[i + 1], sec, { up: u, mat: m_col, smooth: false });
      }
    }
  for (let i = 0; i <= NB_; i++){
    const t = i / NB_;
    for (const sw of [-1, 1])
      prism(mb, P(t, sw, 0), P(t, sw, 1), sec_box(0.30, 0.34), { up: f, mat: m_beam, smooth: false });
    prism(mb, P(t, -1, 1), P(t, 1, 1), sec_box(0.34, 0.34), { up: u, mat: m_beam, smooth: false });
    prism(mb, P(t, -1, 0), P(t, 1, 0), sec_box(0.28, 0.28), { up: u, mat: m_beam, smooth: false });
  }
  for (let i = 0; i < NB_; i++){
    const t0 = i / NB_, t1 = (i + 1) / NB_;
    for (const sw of [-1, 1]){
      prism(mb, P(t0, sw, 0), P(t1, sw, 1), sec_box(0.24, 0.26), { up: s, mat: m_diag, smooth: false });
      prism(mb, P(t0, sw, 1), P(t1, sw, 0), sec_box(0.24, 0.26), { up: s, mat: m_diag, smooth: false });
    }
    prism(mb, P(t0, -1, 0), P(t1, 1, 0), sec_box(0.22, 0.22), { up: u, mat: m_diag, smooth: false });
  }
  const rows: number[][] = [];
  for (let i = 0; i <= NB_; i++){
    const t = i / NB_;
    rows.push([mb.add_v(P(t, -1, 1).add(u.mul(0.22))), mb.add_v(P(t, 1, 1).add(u.mul(0.22)))]);
  }
  for (let i = 0; i < NB_; i++){
    mb.add_f([rows[i][0], rows[i][1], rows[i+1][1], rows[i+1][0]], [[0,0],[2,0],[2,3],[0,3]], false, m_grate);
    mb.add_f([rows[i+1][0], rows[i+1][1], rows[i][1], rows[i][0]], [[0,0],[2,0],[2,3],[0,3]], false, m_grate);
  }
  for (const t of TW.PAD_TS){
    const c0 = P(t, -0.62, 1).add(u.mul(TW.PAD_DZ));
    const c1 = P(t, 0.62, 1).add(u.mul(TW.PAD_DZ));
    prism(mb, c0, c1, sec_box(TW.PAD_L, TW.PAD_H), { up: u, mat: m_dark, smooth: false });
  }
  prism(mb, o.add(s.mul(1.9)).add(u.mul(d_root * 0.10)), o.sub(s.mul(1.9)).add(u.mul(d_root * 0.10)),
        sec_tube(0.85, 16), { up: u, mat: m_col, smooth: true });
  const mast = o.add(u.mul(d_root * 0.95)).sub(f.mul(0.9));
  for (const sw of [-0.72, 0.72]){
    prism(mb, mast.add(s.mul(sw * 1.5)), P(0.50, sw, 1), sec_box(0.46, 0.52),
          { up: s, mat: m_col, smooth: false });
    prism(mb, mast.add(s.mul(sw * 1.5)), P(0.22, sw, 1), sec_box(0.34, 0.40),
          { up: s, mat: m_col, smooth: false });
  }
  prism(mb, mast.sub(s.mul(1.6)), mast.add(s.mul(1.6)), sec_box(0.48, 0.52),
        { up: u, mat: m_col, smooth: false });
}

function carriage(mb: MB, z: number, m_col: number, m_beam: number, m_diag: number, _m_grate: number): void {
  const xf = TW.HW, y0 = 6.30, d = 5.40;
  for (const y of [y0, -y0])
    prism(mb, [xf + 0.4, y, z - d * 0.75], [xf + 0.4, y, z + d * 0.75], sec_box(1.30, 1.40),
          { up: [0, 1, 0], mat: m_col, smooth: false });
  for (const zz of [z - d * 0.75, z - d * 0.15, z + d * 0.45, z + d * 0.75])
    prism(mb, [xf + 0.4, -y0, zz], [xf + 0.4, y0, zz], sec_i(0.62, 0.80, 0.09, 0.12),
          { up: [0, 0, 1], mat: m_beam, smooth: false });
  for (const y of [3.35, -3.35])
    prism(mb, [xf + 0.55, y, z - d * 0.7], [xf + 0.55, y, z + d * 0.7], sec_box(1.25, 1.55),
          { up: [0, 1, 0], mat: m_col, smooth: false });
  for (const y of [y0, -y0])
    for (const zz of [z - d * 0.7, z + d * 0.7])
      prism(mb, [xf + 0.55, y * 0.53, zz], [xf + 0.4, y, zz], sec_box(0.5, 0.55),
            { up: [0, 0, 1], mat: m_diag, smooth: false });
}

function qd_arm(mb: MB, z: number, reach: number, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number, depth = 2.6, wid = 2.4): void {
  const o = new Vec(TW.HW + 0.5, 0.0, z);
  const f = new Vec(1, 0, 0), s = new Vec(0, 1, 0), u = new Vec(0, 0, 1);
  const P = (t: number, sw: number, du: number): Vec => {
    const w = wid * (1.0 - 0.15 * t);
    return o.add(f.mul(reach * t)).add(s.mul(sw * w / 2)).add(u.mul(du * depth));
  };
  const N = 4;
  for (const sw of [-1, 1])
    for (const du of [0, 1])
      for (let i = 0; i < N; i++)
        prism(mb, P(i / N, sw, du), P((i + 1) / N, sw, du), sec_box(0.26, 0.30),
              { up: u, mat: m_col, smooth: false });
  for (let i = 0; i <= N; i++){
    const t = i / N;
    for (const sw of [-1, 1])
      prism(mb, P(t, sw, 0), P(t, sw, 1), sec_box(0.18, 0.20), { up: f, mat: m_beam, smooth: false });
    prism(mb, P(t, -1, 1), P(t, 1, 1), sec_box(0.20, 0.20), { up: u, mat: m_beam, smooth: false });
    if (i < N)
      for (const sw of [-1, 1])
        prism(mb, P(t, sw, 0), P(t + 1 / N, sw, 1), sec_box(0.15, 0.16),
              { up: s, mat: m_diag, smooth: false });
  }
  const rows: number[][] = [];
  for (let i = 0; i <= N; i++)
    rows.push([mb.add_v(P(i / N, -1, 1).add(u.mul(0.18))), mb.add_v(P(i / N, 1, 1).add(u.mul(0.18)))]);
  for (let i = 0; i < N; i++){
    mb.add_f([rows[i][0], rows[i][1], rows[i+1][1], rows[i+1][0]], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
    mb.add_f([rows[i+1][0], rows[i+1][1], rows[i][1], rows[i][0]], [[0,0],[2,0],[2,2],[0,2]], false, m_grate);
  }
  railing(mb, [P(0, -1, 1).add(u.mul(0.2)).slice2(), P(1, -1, 1).add(u.mul(0.2)).slice2(),
               P(1, 1, 1).add(u.mul(0.2)).slice2(), P(0, 1, 1).add(u.mul(0.2)).slice2()],
          z + depth + 0.2, 1.05, m_beam);
  const tip = P(1.0, 0, 0.45);
  prism(mb, tip.sub(f.mul(1.35)), tip.add(f.mul(0.22)), sec_box(2.60, 2.05),
        { up: u, mat: m_dark, smooth: false });
  for (const sw of [-0.8, 0.8])
    prism(mb, new Vec(TW.HW + 0.3, sw * wid * 0.5, z - 4.2), P(0.92, sw, 0.05), sec_box(0.40, 0.44),
          { up: s, mat: m_col, smooth: false });
}

export function towerBuild(): BuildObject[] {
  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3;  /* slots 4 (concrete) and 5 (black) are in the list below but no face uses them */
  const slots = ['tower', 'tower_dark', 'grate', 'dark_metal', 'concrete', 'black'];
  const objs: BuildObject[] = [];
  let mb: MB;

  mb = new MB();
  build_truss(mb, T_MAIN, T_MAIN, T_DARK, T_GRATE);
  build_rails(mb, T_MAIN, T_MAIN, T_DARK);
  build_crown(mb, T_MAIN, T_MAIN, T_DARK, T_GRATE, T_DKM);
  prism(mb, [0, 0, 1.28], [0, 0, TW.BASE_Z], sec_box(TW.W + 0.6, TW.W + 0.6),
        { up: [0, 1, 0], mat: T_DKM, smooth: false });
  objs.push({ name: 'Tower_Struct', mb, smooth: 30, slots, pos: [TW.TOWER_X, 0, 0] });

  mb = new MB();
  carriage(mb, TW.ARM_Z, T_MAIN, T_MAIN, T_DARK, T_GRATE);  /* the source passes a grate slot the body never uses */
  for (const sgn of [1, -1])
    chopstick(mb, [TW.HW + 1.1, sgn * TW.ARM_PIVOT_Y, TW.ARM_Z], sgn * TW.ARM_SPLAY,
              TW.ARM_LEN, T_MAIN, T_MAIN, T_DARK, T_GRATE, T_DKM);
  objs.push({ name: 'Tower_Chopsticks', mb, smooth: 30, slots, pos: [TW.TOWER_X, 0, 0] });

  mb = new MB();
  const reach = (TW.VEHICLE_X - 4.62) - (TW.TOWER_X + TW.HW + 0.5) - 1.13;
  qd_arm(mb, TW.QD_Z, Math.max(reach, 2.0), T_MAIN, T_MAIN, T_DARK, T_GRATE, T_DKM, 2.4, 3.9);
  objs.push({ name: 'Tower_QDArm', mb, smooth: 30, slots, pos: [TW.TOWER_X, 0, 0] });

  return objs;
}
