/**
 * Generates the Starship / Super Heavy / OLIT port from `ref_images/starship.html`.
 *
 *   node tools/starship-gen.mjs
 *
 * WHY A GENERATOR AND NOT HAND-TRANSLATION. The owner's requirement is 100 %
 * geometry + material parity with the demo. Hand-copying 1 900 lines of dense
 * numeric code cannot be argued to be faithful — it can only be spot-checked.
 * This script SLICES line ranges out of the HTML and applies an explicit,
 * asserted patch table, so every line that is not named in a patch is
 * byte-identical to the source by construction, and any drift in the source
 * (a moved line, a changed signature) fails the generator loudly instead of
 * silently producing a near-copy. `tools/starship-parity.mjs` then proves the
 * emitted TypeScript builds the same vertices as the original.
 *
 * Every patch below is one of exactly four kinds:
 *   1. `export` — module scope in the demo, module scope here.
 *   2. TypeScript annotations — types only, no runtime effect.
 *   3. import/`unused local` housekeeping forced by the project's strict
 *      compiler settings (noUnusedLocals). These KEEP the surviving slot
 *      numbers at their source values; nothing is renumbered.
 *   4. ONE structural deviation, called out at its patch: `buildGeometry`
 *      returns plain typed arrays instead of a THREE.BufferGeometry, because
 *      the build runs on a worker thread and three.js cannot cross it.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = readFileSync(join(ROOT, 'ref_images/starship.html'), 'utf8').split('\n')

/** Source lines [a, b] inclusive, 1-indexed the way an editor shows them. */
const lines = (a, b) => SRC.slice(a - 1, b).join('\n')

let written = 0
let patched = 0

function emit(path, header, ranges, patches) {
  let body = ranges.map(([a, b]) => lines(a, b)).join('\n')
  const sourceLines = ranges.reduce((n, [a, b]) => n + (b - a + 1), 0)
  for (const [find, replace, expected = 1] of patches) {
    const hits = body.split(find).length - 1
    if (hits !== expected) {
      throw new Error(
        `${path}: patch expected ${expected}x but source has ${hits}x:\n  ${JSON.stringify(find.slice(0, 90))}`,
      )
    }
    body = body.split(find).join(replace)
    patched++
  }
  const full = join(ROOT, path)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, `${header}${body}\n`)
  written++
  console.log(`  ${path.padEnd(44)} ${String(sourceLines).padStart(4)} source lines, ${patches.length} patches`)
}

console.log('generating from ref_images/starship.html')

/* ==========================================================================
   src/procgen/sslib/mathkit.ts
   ========================================================================== */
emit(
  'src/procgen/sslib/mathkit.ts',
  `/**
 * sslib — python-ish scalar and vector helpers, ported verbatim from the
 * Starship reference build (\`ref_images/starship.html\` §0). GENERATED by
 * tools/starship-gen.mjs; edit the generator, not this file.
 *
 * This is a DIFFERENT lineage from procgen/blenderkit: that kit ports
 * optlib.py (fitted curves, BSP booleans, bevel modifier), this one ports
 * sslib.py (a mesh builder with prisms and lathes). Both reproduce Blender,
 * neither is a rewrite of the other, and a future port should extend whichever
 * kit its own source came from.
 */

/** \`[x, y]\` pair — a 2-D section profile point or a lathe profile point. */
export type Vec2 = [number, number]
/** \`[x, y, z]\` triple — the mesh container's vertex format. */
export type Vec3 = [number, number, number]
/**
 * Anywhere the source hands over a Blender \`Vector\`. The demo is duck-typed
 * and passes a \`Vec\`, a tuple or a bare 3-list interchangeably; every consumer
 * runs it through \`V()\` first, so the union is the honest signature.
 */
export type Pt3 = Vec | Vec3 | number[]

`,
  [[52, 79]],
  [
    ['const PI = Math.PI, TAU = 2 * Math.PI;', 'export const PI = Math.PI, TAU = 2 * Math.PI;'],
    [
      'const sin = Math.sin, cos = Math.cos, tan = Math.tan, sqrt = Math.sqrt;',
      'export const sin = Math.sin, cos = Math.cos, tan = Math.tan, sqrt = Math.sqrt;',
    ],
    [
      'const radians = d => d * Math.PI / 180;',
      'export const radians = (d: number): number => d * Math.PI / 180;',
    ],
    ['function pyround(x){', 'export function pyround(x: number): number {'],
    ['class Vec {\n  constructor(x = 0, y = 0, z = 0)', 'export class Vec {\n  x: number\n  y: number\n  z: number\n  constructor(x = 0, y = 0, z = 0)'],
    ['  add(o){', '  add(o: Vec): Vec {'],
    ['  sub(o){', '  sub(o: Vec): Vec {'],
    ['  mul(s){', '  mul(s: number): Vec {'],
    ['  neg(){', '  neg(): Vec {'],
    ['  dot(o){', '  dot(o: Vec): number {'],
    ['  cross(o){', '  cross(o: Vec): Vec {'],
    ['  get length(){', '  get length(): number {'],
    ['  normalized(){', '  normalized(): Vec {'],
    ['  slice2(){', '  slice2(): Vec2 {'],
    ['function V(p){', 'export function V(p: Pt3): Vec {'],
  ],
)

/* ==========================================================================
   src/procgen/sslib/meshbuilder.ts
   ========================================================================== */
emit(
  'src/procgen/sslib/meshbuilder.ts',
  `/**
 * sslib — the mesh container and its primitives (\`ref_images/starship.html\`
 * §1): MeshBuilder, swept prisms with 2-D sections, and the lathe.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * Faces are n-gons with OPTIONAL per-corner UVs, a per-face smooth flag and a
 * per-face material slot — the four things Blender's \`from_pydata\` +
 * \`shade_auto_smooth\` pipeline needs. \`evalmesh.ts\` turns that into buffers.
 */
import { TAU, V, Vec, cos, pyround, sin, sqrt } from './mathkit'
import type { Pt3, Vec2, Vec3 } from './mathkit'

/** \`prism()\` options — every one is a Blender-side keyword argument. */
export interface PrismOptions {
  up?: Pt3
  cap0?: boolean
  cap1?: boolean
  mat?: number
  smooth?: boolean
  ext0?: number
  ext1?: number
  twist?: number
  scale1?: number
}

/** \`lathe()\` options — likewise. */
export interface LatheOptions {
  mat?: number
  cap_bottom?: boolean
  cap_top?: boolean
  smooth?: boolean
  tile_w?: number | null
  a0?: number
  a1?: number
  center?: Vec2
  flip?: boolean
  sharp_idx?: number[]
}

`,
  [
    [84, 99],
    [101, 145],
    [147, 160],
    [162, 246],
  ],
  [
    ['class MB {\n  constructor(){ this.v = []; this.f = []; this.uv = []; this.sm = []; this.mat = []; }',
      `export class MB {
  v: Vec3[]
  f: number[][]
  uv: Array<Vec2[] | null>
  sm: boolean[]
  mat: number[]
  constructor(){ this.v = []; this.f = []; this.uv = []; this.sm = []; this.mat = []; }`],
    ['  add_v(p){', '  add_v(p: Pt3): number {'],
    ['  add_f(idx, uvq = null, smooth = false, mat = 0){',
      '  add_f(idx: number[], uvq: Vec2[] | null = null, smooth = false, mat = 0): void {'],
    ['  offset(){ return this.v.length; }', '  offset(): number { return this.v.length; }'],
    ['function _basis(p0, p1, up_hint){',
      'function _basis(p0: Pt3, p1: Pt3, up_hint: Pt3): [Vec, Vec, Vec, number] {'],
    ['function prism(mb, p0, p1, section, o = {}){',
      'export function prism(mb: MB, p0: Pt3, p1: Pt3, section: Vec2[], o: PrismOptions = {}): number {'],
    ['const sec_box = (w, h) =>', 'export const sec_box = (w: number, h: number): Vec2[] =>'],
    ['function sec_i(w, h, tw, tf){', 'export function sec_i(w: number, h: number, tw: number, tf: number): Vec2[] {'],
    ['function sec_tube(r, n = 12){', 'export function sec_tube(r: number, n = 12): Vec2[] {'],
    ['  const p = [];\n  for (let k = 0; k < n; k++) p.push([r * cos(TAU * k / n), r * sin(TAU * k / n)]);',
      '  const p: Vec2[] = [];\n  for (let k = 0; k < n; k++) p.push([r * cos(TAU * k / n), r * sin(TAU * k / n)]);'],
    ['function lathe(mb, profile, segs, o = {}){',
      'export function lathe(mb: MB, profile: Vec2[], segs: number, o: LatheOptions = {}): number {'],
    ['  const vs = [0.0];', '  const vs: number[] = [0.0];'],
    ['  const us = [];\n  for (let k = 0; k < n; k++){\n    const r = Math.max(profile[k][0], 1e-4);',
      '  const us: number[] = [];\n  for (let k = 0; k < n; k++){\n    const r = Math.max(profile[k][0], 1e-4);'],
    ['    let quad = [A, B, C, D];\n      let uvq  = [[u0, vs[k]], [u1, vs[k]], [u2, vs[k+1]], [u3, vs[k+1]]];',
      '    let quad = [A, B, C, D];\n      let uvq: Vec2[] = [[u0, vs[k]], [u1, vs[k]], [u2, vs[k+1]], [u3, vs[k+1]]];'],
    ['    const ring = []; for (let s = 0; s < ns; s++) ring.push(i0 + s);',
      '    const ring: number[] = []; for (let s = 0; s < ns; s++) ring.push(i0 + s);'],
    ['    const ring = []; for (let s = 0; s < ns; s++) ring.push(i0 + (n - 1) * ns + s);',
      '    const ring: number[] = []; for (let s = 0; s < ns; s++) ring.push(i0 + (n - 1) * ns + s);'],
    ['function ring_stack(z0, z1, r, ring_h, lip = 0.010, groove = 0.030){\n  const prof = [[r, z0]];',
      'export function ring_stack(z0: number, z1: number, r: number, ring_h: number, lip = 0.010, groove = 0.030): Vec2[] {\n  const prof: Vec2[] = [[r, z0]];'],
    // prism() reads section entries and the caps build reversed rings.
    ['  const i0 = mb.offset();\n  const ct = cos(twist), st = sin(twist);',
      '  const i0 = mb.offset();\n  const ct = cos(twist), st = sin(twist);'],
    ['  if (cap0){ const r = []; for (let i = i0 + n - 1; i > i0 - 1; i--) r.push(i); mb.add_f(r, null, false, mat); }',
      '  if (cap0){ const r: number[] = []; for (let i = i0 + n - 1; i > i0 - 1; i--) r.push(i); mb.add_f(r, null, false, mat); }'],
    ['  if (cap1){ const r = []; for (let i = i0 + n; i < i0 + 2 * n; i++) r.push(i); mb.add_f(r, null, false, mat); }',
      '  if (cap1){ const r: number[] = []; for (let i = i0 + n; i < i0 + 2 * n; i++) r.push(i); mb.add_f(r, null, false, mat); }'],
  ],
)

/* ==========================================================================
   src/procgen/sslib/evalmesh.ts
   ========================================================================== */
emit(
  'src/procgen/sslib/evalmesh.ts',
  `/**
 * sslib — Blender's EVALUATED mesh, reproduced (\`ref_images/starship.html\`
 * §2). GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * The one structural deviation from the demo in this whole port lives at the
 * bottom of \`buildGeometry\`: it returns plain typed arrays rather than a
 * THREE.BufferGeometry, because the build runs on a worker thread and three.js
 * must not be imported there. The arrays are the demo's arrays, element for
 * element — \`tools/starship-parity.mjs\` asserts it.
 */
import { V, Vec, radians } from './mathkit'
import type { Vec3 } from './mathkit'
import type { MB } from './meshbuilder'

/** One material-slot draw range, in vertices (the geometry is non-indexed). */
export interface GeometryGroup {
  start: number
  count: number
  materialIndex: number
}

export interface GeometryPayload {
  position: Float32Array
  normal: Float32Array
  uv: Float32Array
  groups: GeometryGroup[]
  tris: number
}

/**
 * One emitted object: a filled mesh container plus how Blender was told to
 * shade it (\`smooth\` is the shade_auto_smooth angle in degrees, or null for
 * per-face flags) and which material slot list it indexes into.
 */
export interface BuildObject {
  name: string
  mb: MB
  smooth: number | null
  slots: readonly string[]
  pos?: Vec3
  rotZ?: number
}

`,
  [
    [258, 269],
    [271, 318],
    [320, 492],
  ],
  [
    ['function newell(Vs, f){', 'function newell(Vs: Vec3[], f: number[]): Vec3 {'],
    ['function earClip(pts){', 'function earClip(pts: Array<[number, number]>): Array<[number, number, number]> {'],
    ['  const ar = (a, b, c) => (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0]);',
      '  const ar = (a: [number, number], b: [number, number], c: [number, number]): number => (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0]);'],
    ['  let idx = []; for (let i = 0; i < n; i++) idx.push(i);\n  const tris = [];',
      '  let idx: number[] = []; for (let i = 0; i < n; i++) idx.push(i);\n  const tris: Array<[number, number, number]> = [];'],
    ['function triangulate(Vs, f, nrm){', 'function triangulate(Vs: Vec3[], f: number[], nrm: Vec3): Array<[number, number, number]> {'],
    ['  let e = V(Vs[f[1]]).sub(p0);', '  const e = V(Vs[f[1]]).sub(p0);'],
    ['        let cd = (e1x*e2x + e1y*e2y + e1z*e2z) / (l1 * l2);',
      '        const cd = (e1x*e2x + e1y*e2y + e1z*e2z) / (l1 * l2);'],
    ['  const pts = f.map(vi => { const q = V(Vs[vi]).sub(p0); return [q.dot(ax), q.dot(ay)]; });',
      '  const pts = f.map((vi): [number, number] => { const q = V(Vs[vi]).sub(p0); return [q.dot(ax), q.dot(ay)]; });'],
    ['function buildGeometry(mb, smoothAngleDeg){',
      'export function buildGeometry(mb: MB, smoothAngleDeg: number | null): GeometryPayload {'],
    ['  const pass1 = [];', '  const pass1: number[] = [];'],
    ['  const seen = new Set(), keep = [];', '  const seen = new Set<string>(), keep: number[] = [];'],
    ['  const vPairs = new Array(nv);', '  const vPairs: Array<number[] | undefined> = new Array(nv);'],
    ['  const find = (p, i) => { while (p[i] !== i) { p[i] = p[p[i]]; i = p[i]; } return i; };',
      '  const find = (p: Int32Array, i: number): number => { while (p[i] !== i) { p[i] = p[p[i]]; i = p[i]; } return i; };'],
    ['    const local = new Map();', '    const local = new Map<number, number>();'],
    ['    const acc = new Map();', '    const acc = new Map<number, [number, number, number]>();'],
    ['      let a = acc.get(r);\n      if (a === undefined){ a = [0, 0, 0]; acc.set(r, a); }',
      '      let a = acc.get(r);\n      if (a === undefined){ a = [0, 0, 0]; acc.set(r, a); }'],
    ['  const perMat = new Map();', '  const perMat = new Map<number, number>();'],
    ['  let total = 0; const off = new Map();', '  let total = 0; const off = new Map<number, number>();'],
    ['  const cur = new Map(); for (const m of order) cur.set(m, off.get(m));',
      '  const cur = new Map<number, number>(); for (const m of order) cur.set(m, off.get(m)!);'],
    ['  for (const m of order){ off.set(m, total); total += perMat.get(m); }',
      '  for (const m of order){ off.set(m, total); total += perMat.get(m)!; }'],
    ['      let ti = cur.get(m); cur.set(m, ti + 1);', '      const ti = cur.get(m)!; cur.set(m, ti + 1);'],
    // ---- the one structural deviation: payload out, not BufferGeometry.
    [`  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  g.setAttribute('normal',   new THREE.BufferAttribute(nor, 3));
  g.setAttribute('uv',       new THREE.BufferAttribute(uvs, 2));
  for (const m of order) g.addGroup(off.get(m) * 3, perMat.get(m) * 3, m);
  g.computeBoundingSphere();
  g.userData.tris = total;
  return g;
}`,
      `  // DEVIATION (the only one in the port): the demo builds a
  // THREE.BufferGeometry here. This runs on a worker thread, so it hands back
  // the same arrays as a transferable payload and the main thread wraps them.
  // Group ranges are identical — \`addGroup(off*3, perMat*3, m)\`.
  const groups: GeometryGroup[] = [];
  for (const m of order) groups.push({ start: off.get(m)! * 3, count: perMat.get(m)! * 3, materialIndex: m });
  return { position: pos, normal: nor, uv: uvs, groups, tris: total };
}`],
  ],
)

/* ==========================================================================
   src/procgen/sslib/blenderNodes.ts
   ========================================================================== */
emit(
  'src/procgen/sslib/blenderNodes.ts',
  `/**
 * sslib — Blender's shader nodes as raw WGSL (\`ref_images/starship.html\` §3).
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * Blender's lookup3 hash, Perlin/fBm noise, white noise and the HexGrid node
 * group are transcribed as WGSL functions and injected with \`wgsl()\`, so the
 * procedural patterns match the Blender build texel for texel rather than
 * approximately. This is the FIRST raw-WGSL in the project — everything else
 * is TSL — and it is deliberate: TSL's own \`mx_noise\` is a different noise
 * basis, and swapping it in would change every material in the port.
 *
 * NOTE the difference from procgen/blenderkit/blenderNoise.ts, which ports the
 * same Blender hash as TSL nodes for the Optimus build. Two ports of one
 * source, kept apart on purpose: each reproduces the demo it came from, and
 * merging them would put one demo's pixels at the mercy of the other's edits.
 */
import { MeshPhysicalNodeMaterial, MeshStandardNodeMaterial } from 'three/webgpu'
import type { Node } from 'three/webgpu'
import {
  Fn, wgsl, wgslFn, float, vec3, uv, positionLocal, positionView,
  normalView, mix, max, abs, sign, dFdx, dFdy, cross, dot, normalize,
} from 'three/tsl'
import { DoubleSide } from 'three'

`,
  [
    [498, 656],
    [658, 709],
  ],
  [
    ['const BL = wgsl(`', 'const BL = /*@__PURE__*/ wgsl(`'],
    ['const wNoise2 = wgslFn(', 'const wNoise2 = /*@__PURE__*/ wgslFn('],
    ['const wNoise3 = wgslFn(', 'const wNoise3 = /*@__PURE__*/ wgslFn('],
    ['const wWhite3 = wgslFn(', 'export const wWhite3 = /*@__PURE__*/ wgslFn('],
    ['const wHex    = wgslFn(', 'export const wHex    = /*@__PURE__*/ wgslFn('],
    ['const N2 = (co, detail, rough, dist = 0.0) =>\n  wNoise2({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) });',
      'export const N2 = (co: Node<\'vec2\'>, detail: number, rough: number, dist = 0.0): Node<\'float\'> =>\n  wNoise2({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) }) as unknown as Node<\'float\'>;'],
    ['const N3 = (co, detail, rough, dist = 0.0) =>\n  wNoise3({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) });',
      'export const N3 = (co: Node<\'vec3\'>, detail: number, rough: number, dist = 0.0): Node<\'float\'> =>\n  wNoise3({ co, detail: float(detail), roughness: float(rough), lacunarity: float(2.0), distortion: float(dist) }) as unknown as Node<\'float\'>;'],
    ['function rampF(fac, stops){\n  let res = float(stops[0][1]);',
      'export function rampF(fac: Node<\'float\'>, stops: Array<[number, number]>): Node<\'float\'> {\n  let res: Node<\'float\'> = float(stops[0][1]);'],
    ['const madd  = (a, b, c) => a.mul(b).add(c);',
      'export const madd = (a: Node<\'float\'>, b: number, c: Node<\'float\'>): Node<\'float\'> => a.mul(b).add(c);'],
    ['const maddC = (a, b, c) => a.mul(b).add(c).clamp(0, 1);',
      'export const maddC = (a: Node<\'float\'>, b: number, c: Node<\'float\'>): Node<\'float\'> => a.mul(b).add(c).clamp(0, 1);'],
    ['const blBump = Fn(([height, strength, dist]) => {', 'export const blBump = /*@__PURE__*/ Fn(([height, strength, dist]: [Node<\'float\'>, Node<\'float\'>, Node<\'float\'>]) => {'],
    ['const UV3 = () => vec3(uv().x, uv().y, 0.0);', 'export const UV3 = (): Node<\'vec3\'> => vec3(uv().x, uv().y, 0.0);'],
    ['const OBJ = () => positionLocal;', 'export const OBJ = (): Node<\'vec3\'> => positionLocal;'],
    ['function newmat(name, spec){', 'export function newmat(name: string, spec?: number): MeshStandardNodeMaterial {'],
    ['    m = new THREE.MeshPhysicalNodeMaterial();', '    m = new MeshPhysicalNodeMaterial();'],
    ['    m = new THREE.MeshStandardNodeMaterial();', '    m = new MeshStandardNodeMaterial();'],
    ['  let m;', '  let m: MeshStandardNodeMaterial;'],
    ['    m.ior = 1.5;\n    m.specularIntensity = spec / 0.5;',
      '    (m as MeshPhysicalNodeMaterial).ior = 1.5;\n    (m as MeshPhysicalNodeMaterial).specularIntensity = spec / 0.5;'],
    ['  m.side = THREE.DoubleSide;', '  m.side = DoubleSide;'],
    ['  m.flatShading = false;', '  (m as MeshStandardNodeMaterial).flatShading = false;'],
  ],
)

/* ==========================================================================
   src/starship/starshipMaterials.ts
   ========================================================================== */
emit(
  'src/starship/starshipMaterials.ts',
  `/**
 * The 20 node materials of the Starship / OLIT build (\`ref_images/starship.html\`
 * §3, \`mats.py\`). GENERATED by tools/starship-gen.mjs; edit the generator.
 *
 * Every one is DoubleSide, because the Blender source has
 * use_backface_culling = False and the port needs it: the TPS shell, the hot
 * stage and most lathes here are open shells whose caps were never authored.
 * Turning culling on would put holes in the vehicle, not save fill rate.
 *
 * They are lit by the park's own Mars sun and baked sky environment, not by
 * the demo's studio rig — the demo's three-light studio and its synthetic
 * equirect are NOT part of "geometry and material", and importing them would
 * mean a second sun over the valley.
 */
import type { MeshPhysicalNodeMaterial, MeshStandardNodeMaterial, Node } from 'three/webgpu'
import { float, fract, floor, max, min, mix, uv, vec2, vec3 } from 'three/tsl'
import {
  N2, N3, OBJ, UV3, blBump, madd, maddC, newmat, rampF, wHex, wWhite3,
} from '../procgen/sslib/blenderNodes'

/** Keyed by the slot names every builder's \`slots\` list uses. */
export type StarshipMaterials = Record<string, MeshStandardNodeMaterial>

`,
  [[711, 884]],
  [
    ['function mat_steel(name, { ring_h = 1.83, base = 0.60, rough = 0.255,\n                           tint = [1.0, 0.995, 0.985], dirt = 0.0, seed = 0.0 } = {}){',
      `function mat_steel(name: string, { ring_h = 1.83, base = 0.60, rough = 0.255,
                           tint = [1.0, 0.995, 0.985], dirt = 0.0, seed = 0.0 }: {
                           ring_h?: number, base?: number, rough?: number,
                           tint?: number[], dirt?: number, seed?: number } = {}): MeshStandardNodeMaterial {`],
    ['  const wn = wWhite3({ co: vec3(floor(ridx), float(seed), float(0.0)) });',
      '  const wn = wWhite3({ co: vec3(floor(ridx), float(seed), float(0.0)) }) as unknown as Node<\'float\'>;'],
    ['  const hx = wHex({ co: UV3(), scale: float(tile) });',
      '  const hx = wHex({ co: UV3(), scale: float(tile) }) as unknown as Node<\'vec4\'>;'],
    ['function mat_tiles(name, { tile = 0.166, dark = 0.020, rough = 0.52 } = {}){',
      'function mat_tiles(name: string, { tile = 0.166, dark = 0.020, rough = 0.52 }: { tile?: number, dark?: number, rough?: number } = {}): MeshStandardNodeMaterial {'],
    ['function mat_tower(name, { base = 0.052, rough = 0.66, rust = 0.5, metal = 0.55 } = {}){',
      'function mat_tower(name: string, { base = 0.052, rough = 0.66, rust = 0.5, metal = 0.55 }: { base?: number, rough?: number, rust?: number, metal?: number } = {}): MeshStandardNodeMaterial {'],
    ['function mat_engine(name, { base = 0.075, rough = 0.34, warm = 0.0 } = {}){',
      'function mat_engine(name: string, { base = 0.075, rough = 0.34, warm = 0.0 }: { base?: number, rough?: number, warm?: number } = {}): MeshStandardNodeMaterial {'],
    ['function mat_concrete(name, { base = 0.30, rough = 0.85 } = {}){',
      'function mat_concrete(name: string, { base = 0.30, rough = 0.85 }: { base?: number, rough?: number } = {}): MeshStandardNodeMaterial {'],
    ['function mat_flat(name, col, rough = 0.55, metal = 0.0, spec = 0.5){',
      'function mat_flat(name: string, col: number[], rough = 0.55, metal = 0.0, spec = 0.5): MeshStandardNodeMaterial {'],
    ['function mat_painted(name, col, rough = 0.5, metal = 0.1, wear = 0.35, scale = 1.5){',
      'function mat_painted(name: string, col: number[], rough = 0.5, metal = 0.1, wear = 0.35, scale = 1.5): MeshStandardNodeMaterial {'],
    ['function buildMaterials(){\n  const M = {};', 'export function buildStarshipMaterials(): StarshipMaterials {\n  const M: StarshipMaterials = {};'],
    // `newmat` returns NodeMaterial; the physical branch is the only one with
    // specularIntensity, and only mat_tiles/mat_concrete/mat_flat reach it.
    ['  const m = newmat(name, 0.26);', '  const m = newmat(name, 0.26) as MeshPhysicalNodeMaterial;'],
    ['  const m = newmat(name, 0.13);', '  const m = newmat(name, 0.13) as MeshPhysicalNodeMaterial;'],
    ['  const m = newmat(name, spec);', '  const m = newmat(name, spec) as MeshPhysicalNodeMaterial;'],
    // TSL node assignments: the material fields are typed loosely upstream.
    ['  m.roughnessNode = maddC(seam2, 0.26, rspk);', '  m.roughnessNode = maddC(seam2, 0.26, rspk) as unknown as Node<\'float\'>;'],
    ['    m.colorNode = mix(col, dcol, float(dirt));', '    m.colorNode = mix(col, dcol, float(dirt)) as unknown as Node<\'vec3\'>;'],
    ['    m.colorNode = col;', '    m.colorNode = col as unknown as Node<\'vec3\'>;'],
  ],
)

/* ==========================================================================
   src/starship/parts/ship.ts
   ========================================================================== */
emit(
  'src/starship/parts/ship.ts',
  `/**
 * Starship (the upper stage) — \`ref_images/starship.html\` §4, \`ship.py\`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * \`raptor()\` and \`surface_patch()\` are exported because booster.py calls both;
 * in the single-file demo they were simply in scope.
 */
import { MB, lathe, prism, ring_stack, sec_tube } from '../../procgen/sslib/meshbuilder'
import { PI, TAU, Vec, cos, radians, sin, sqrt, tan } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'

/** One flap's plan: hinge band, chord, sweep and thickness taper. */
export interface FlapSpec {
  z_bot: number
  z_top: number
  chord: number
  sweep_deg: number
  t_root: number
  t_tip: number
  phi_deg: number
  bot_sweep_deg: number
}

interface FlapBuildSpec extends FlapSpec {
  mat_top: number
  mat_bot: number
  mat_edge: number
  nspan?: number
  nchord?: number
}

`,
  [[888, 1271]],
  [
    ['const SHIP = {};', `export const SHIP: {
  R: number; SHIP_H: number; NOSE_L: number; BARREL_TOP: number; RING: number;
  SEG: number; NS_TPS: number; TPS_T: number; TPS_GAP: number;
  AFT_FLAP: FlapSpec; FWD_FLAP: FlapSpec;
} = {} as never;`],
    ['function nose_pts(n = 96){\n  const Lz = SHIP.NOSE_L, Rr = SHIP.R, a = OGIVE_MIX;',
      'function nose_pts(n = 96): Vec2[] {\n  const Lz = SHIP.NOSE_L, Rr = SHIP.R, a = OGIVE_MIX;'],
    ['  const pts = [];\n  for (let k = 0; k <= n; k++){\n    const h = Lz * Math.pow(k / n, 0.94);',
      '  const pts: Vec2[] = [];\n  for (let k = 0; k <= n; k++){\n    const h = Lz * Math.pow(k / n, 0.94);'],
    ['function ship_hull_profile(seams = true){', 'function ship_hull_profile(seams = true): Vec2[] {'],
    ['  let p = [[R - 0.12, 0.0], [R - 0.12, 0.06], [R, 0.17]];',
      '  let p: Vec2[] = [[R - 0.12, 0.0], [R - 0.12, 0.06], [R, 0.17]];'],
    ['  let acc = 0.0, last = npts[0];\n  const out = [];',
      '  let acc = 0.0, last: Vec2 = npts[0];\n  const out: Vec2[] = [];'],
    ['let _SMOOTH = null;\nfunction hull_r(z){', 'let _SMOOTH: Vec2[] | null = null;\nexport function hull_r(z: number): number {'],
    ['function offset_profile(prof, d){\n  const n = prof.length, out = [];',
      'function offset_profile(prof: Vec2[], d: number): Vec2[] {\n  const n = prof.length, out: Vec2[] = [];'],
    ['function tps_shell(mb, prof0, half_fn, thick, mat_out, mat_side, jitter, ns = SHIP.NS_TPS, gap = SHIP.TPS_GAP){',
      `function tps_shell(
  mb: MB, prof0: Vec2[], half_fn: (k: number, r: number, z: number) => number,
  thick: number, mat_out: number, mat_side: number, jitter: number,
  ns = SHIP.NS_TPS, gap = SHIP.TPS_GAP,
): void {`],
    ['  const halves = [];', '  const halves: number[] = [];'],
    ['  const vlen = [0.0];', '  const vlen: number[] = [0.0];'],
    ['  const O = [], I = [];', '  const O: number[][] = [], I: number[][] = [];'],
    ['    for (const [side, flip] of [[0, false], [ns, true]]){',
      '    for (const [side, flip] of [[0, false], [ns, true]] as Array<[number, boolean]>){'],
    ['  for (const [k, rev] of [[0, true], [n - 1, false]]){',
      '  for (const [k, rev] of [[0, true], [n - 1, false]] as Array<[number, boolean]>){'],
    ['    const rowO = [], rowI = [];', '    const rowO: number[] = [], rowI: number[] = [];'],
    ['function flap_solid(mb, hinge_r, az, p){',
      'function flap_solid(mb: MB, hinge_r: ((z: number) => number) | number, az: number, p: FlapBuildSpec): void {'],
    ['  const hr = (typeof hinge_r === \'function\') ? hinge_r : (() => hinge_r);',
      '  const hr: (z: number) => number = (typeof hinge_r === \'function\') ? hinge_r : (() => hinge_r);'],
    ['  const zt = u => z_top - u * chord * swp;\n  const zb = u => z_bot + u * chord * bswp;\n  const half_t = u => {',
      '  const zt = (u: number): number => z_top - u * chord * swp;\n  const zb = (u: number): number => z_bot + u * chord * bswp;\n  const half_t = (u: number): number => {'],
    ['  const top = [], bot = [];', '  const top: number[][] = [], bot: number[][] = [];'],
    ['    const rowT = [], rowB = [];', '    const rowT: number[] = [], rowB: number[] = [];'],
    ['  const quad = (rows, i, j, flip, mat) => {',
      '  const quad = (rows: number[][], i: number, j: number, flip: boolean, mat: number): void => {'],
    ['    const uvq = [[uu, vv], [uu2, vv], [uu2, vv2], [uu, vv2]];',
      '    const uvq: Vec2[] = [[uu, vv], [uu2, vv], [uu2, vv2], [uu, vv2]];'],
    ['  for (const [j, flip] of [[0, true], [nspan, false]]){',
      '  for (const [j, flip] of [[0, true], [nspan, false]] as Array<[number, boolean]>){'],
    ['function hinge_fairing(mb, az, z0, z1, r_fn, rt, mat, seg = 26, nz = 22){',
      'function hinge_fairing(mb: MB, az: number, z0: number, z1: number, r_fn: ((z: number) => number) | number, rt: number, mat: number, seg = 26, nz = 22): void {'],
    ['  const idx = [];\n  for (let i = 0; i <= nz; i++){', '  const idx: number[][] = [];\n  for (let i = 0; i <= nz; i++){'],
    ['    const row = [];\n    for (let k = 0; k < seg; k++){\n      const ang = TAU * k / seg;',
      '    const row: number[] = [];\n    for (let k = 0; k < seg; k++){\n      const ang = TAU * k / seg;'],
    ['function raptor(mb, x, y, z, exit_r, len, mat_body, mat_noz, seg = 32, vac = false){',
      'export function raptor(mb: MB, x: number, y: number, z: number, exit_r: number, len: number, mat_body: number, mat_noz: number, seg = 32, vac = false): void {'],
    ['  const prof = [];\n  const n = 24;', '  const prof: Vec2[] = [];\n  const n = 24;'],
    ['  const lip = [[exit_r, z_exit], [exit_r * 1.030, z_exit + exit_r * 0.055],',
      '  const lip: Vec2[] = [[exit_r, z_exit], [exit_r * 1.030, z_exit + exit_r * 0.055],'],
    ['  const ph = [[throat_r * 2.10, z - 0.010 * len], [throat_r * 2.55, z + 0.030 * len],',
      '  const ph: Vec2[] = [[throat_r * 2.10, z - 0.010 * len], [throat_r * 2.55, z + 0.030 * len],'],
    ['const hull_pt = (a, r, z) => [r * sin(a), -r * cos(a), z];',
      'const hull_pt = (a: number, r: number, z: number): Vec3 => [r * sin(a), -r * cos(a), z];'],
    ['function surface_patch(mb, a_c, z_c, w, h, r, bulge, mat, na = 8, nz = 1, smooth = true){',
      'export function surface_patch(mb: MB, a_c: number, z_c: number, w: number, h: number, r: number, bulge: number, mat: number, na = 8, nz = 1, smooth = true): void {'],
    ['  const top = [], base = [];', '  const top: number[][] = [], base: number[][] = [];'],
    ['    const rt = [], rb = [];', '    const rt: number[] = [], rb: number[] = [];'],
    ['  const ruv = [];', '  const ruv: Vec2[] = [];'],
    ['function shipBuild(){', 'export function shipBuild(): BuildObject[] {'],
    ['  const S_STEEL = 0, S_TILE = 1, S_TILEN = 2, S_BLACK = 3, S_ENG = 4, S_NOZ = 5, S_DKM = 6, S_DIRTY = 7;',
      '  const S_STEEL = 0, S_TILE = 1, S_BLACK = 3, S_ENG = 4, S_NOZ = 5, S_DKM = 6, S_DIRTY = 7;  /* slot 2 (tiles_nose) is in the list below but no face uses it */'],
    ['  const objs = [];\n  let mb;', '  const objs: BuildObject[] = [];\n  let mb: MB;'],
    ['  const half_fn = (k, r, z) => {', '  const half_fn = (_k: number, _r: number, z: number): number => {'],
    ['  const hr = z => hull_r(z) + 0.10;', '  const hr = (z: number): number => hull_r(z) + 0.10;'],
    ['    const n = 10, rows = [];', '    const n = 10, rows: number[][] = [];'],
    ['      const row = [];\n      for (let k = 0; k <= n; k++){\n        const aa = a0 - (w / R) / 2 + (w / R) * k / n;',
      '      const row: number[] = [];\n      for (let k = 0; k <= n; k++){\n        const aa = a0 - (w / R) / 2 + (w / R) * k / n;'],
  ],
)

/* ==========================================================================
   src/starship/parts/booster.ts
   ========================================================================== */
emit(
  'src/starship/parts/booster.ts',
  `/**
 * Super Heavy (the booster) — \`ref_images/starship.html\` §5, \`booster.py\`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 */
import { MB, lathe, prism, ring_stack, sec_box, sec_tube } from '../../procgen/sslib/meshbuilder'
import { PI, TAU, Vec, cos, pyround, radians, sin, sqrt } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'
import { raptor, surface_patch } from './ship'

/**
 * BOOST_H etc. come from the literal; BODY_TOP is assigned on the next source
 * line. The assertion is what lets the demo's two-step stay two steps — the
 * numbers themselves are checked by tools/starship-parity.mjs, not by tsc.
 */
interface BoosterConfig {
  R: number
  BOOST_H: number
  HS_H: number
  RING: number
  SEG: number
  GF_Z: number
  GF_N: number
  GF_AZ0: number
  CH_Z: number
  BODY_TOP: number
}

`,
  [[1275, 1484]],
  [
    ['const BST = { R: 4.5,', 'export const BST = { R: 4.5,'],
    ['              GF_Z: 65.30, GF_N: 4, GF_AZ0: 45.0, CH_Z: 61.20 };',
      '              GF_Z: 65.30, GF_N: 4, GF_AZ0: 45.0, CH_Z: 61.20 } as BoosterConfig;'],
    ['function booster_hull_profile(){', 'function booster_hull_profile(): Vec2[] {'],
    ['  let p = [[R - 0.14, 0.0], [R - 0.14, 0.05], [R, 0.16]];',
      '  let p: Vec2[] = [[R - 0.14, 0.0], [R - 0.14, 0.05], [R, 0.16]];'],
    ['function hot_stage(mb, z0, m_ring, m_lat, m_dark, n_zig = 24, seg = BST.SEG){',
      'function hot_stage(mb: MB, z0: number, m_ring: number, m_lat: number, m_dark: number, n_zig = 24, seg = BST.SEG): void {'],
    ['  const dome = [];', '  const dome: Vec2[] = [];'],
    ['    const p0 = [ro * cos(a0), ro * sin(a0), zb];\n    const p1 = [ro * cos(a1), ro * sin(a1), zt];\n    const p2 = [ro * cos(a2), ro * sin(a2), zb];',
      '    const p0: Vec3 = [ro * cos(a0), ro * sin(a0), zb];\n    const p1: Vec3 = [ro * cos(a1), ro * sin(a1), zt];\n    const p2: Vec3 = [ro * cos(a2), ro * sin(a2), zb];'],
    ['      const up = [cos((a0 + a2) / 2), sin((a0 + a2) / 2), 0.0];',
      '      const up: Vec3 = [cos((a0 + a2) / 2), sin((a0 + a2) / 2), 0.0];'],
    ['function grid_fin(mb, az_deg, z, m_frame, m_lat, m_dark,\n                  span = 4.35, width = 3.90, thick = 0.74, roll = 0.0, r_in = null){',
      `function grid_fin(mb: MB, az_deg: number, z: number, m_frame: number, m_lat: number, _m_dark: number,
                  span = 4.35, width = 3.90, thick = 0.74, roll = 0.0, r_in: number | null = null): void {`],
    ['  const P = (s, w) => origin.add(rad.mul(s)).add(wv.mul(w));',
      '  const P = (s: number, w: number): Vec => origin.add(rad.mul(s)).add(wv.mul(w));'],
    ['function blister(mb, az_deg, z, mat, hgt, wid, out, pz = 0.62, pa = 0.55, NZ = 14, NA = 20, z_bias = 0.0){',
      'function blister(mb: MB, az_deg: number, z: number, mat: number, hgt: number, wid: number, out: number, pz = 0.62, pa = 0.55, NZ = 14, NA = 20, z_bias = 0.0): void {'],
    ['  const rows = [];\n  for (let i = 0; i <= NZ; i++){\n    const t = -1.0 + 2.0 * i / NZ;',
      '  const rows: number[][] = [];\n  for (let i = 0; i <= NZ; i++){\n    const t = -1.0 + 2.0 * i / NZ;'],
    ['    const row = [];\n    for (let j = 0; j <= NA; j++){\n      const s = -1.0 + 2.0 * j / NA;\n      let ea',
      '    const row: number[] = [];\n    for (let j = 0; j <= NA; j++){\n      const s = -1.0 + 2.0 * j / NA;\n      let ea'],
    ['const gf_fairing = (mb, az_deg, z, mat) =>',
      'const gf_fairing = (mb: MB, az_deg: number, z: number, mat: number): void =>'],
    ['function chine(mb, az_deg, z, mat, ln = 5.40, out = 0.62, wid = 1.90){',
      'function chine(mb: MB, az_deg: number, z: number, mat: number, ln = 5.40, out = 0.62, wid = 1.90): void {'],
    ['  const rows = [];\n  for (let i = 0; i <= NZ; i++){\n    const t = i / NZ;',
      '  const rows: number[][] = [];\n  for (let i = 0; i <= NZ; i++){\n    const t = i / NZ;'],
    ['    const row = [];\n    for (let j = 0; j <= NA; j++){\n      const s = -1.0 + 2.0 * j / NA;\n      const b',
      '    const row: number[] = [];\n    for (let j = 0; j <= NA; j++){\n      const s = -1.0 + 2.0 * j / NA;\n      const b'],
    ['function raceway(mb, az_deg, z0, z1, w, bul, mat, n = 12){',
      'function raceway(mb: MB, az_deg: number, z0: number, z1: number, w: number, bul: number, mat: number, n = 12): void {'],
    ['  const rows = [];\n  for (const z of [z0, z1]){\n    const row = [];',
      '  const rows: number[][] = [];\n  for (const z of [z0, z1]){\n    const row: number[] = [];'],
    ['function boosterBuild(){', 'export function boosterBuild(): BuildObject[] {'],
    ['  const B_ST = 0, B_DIRTY = 1, B_HOT = 2, B_BLK = 3, B_ENG = 4, B_NOZ = 5, B_DKM = 6, B_GF = 7;',
      '  const B_ST = 0, B_HOT = 2, B_BLK = 3, B_ENG = 4, B_NOZ = 5, B_DKM = 6, B_GF = 7;  /* slot 1 (steel_dirty) is in the list below but no face uses it */'],
    ['  const objs = [];\n  let mb;', '  const objs: BuildObject[] = [];\n  let mb: MB;'],
    ['  for (const [n, r, off] of [[3, 1.00, 0.0], [10, 2.66, 18.0], [20, 3.90, 0.0]])',
      '  for (const [n, r, off] of [[3, 1.00, 0.0], [10, 2.66, 18.0], [20, 3.90, 0.0]] as Array<[number, number, number]>)'],
  ],
)

/* ==========================================================================
   src/starship/parts/tower.ts
   ========================================================================== */
emit(
  'src/starship/parts/tower.ts',
  `/**
 * The OLIT (tower, chopsticks, QD arm) — \`ref_images/starship.html\` §6,
 * \`tower.py\`. GENERATED by tools/starship-gen.mjs; edit the generator.
 *
 * \`TW\` is MUTATED by the assembly before \`towerBuild()\` runs: the catch arms'
 * height and the vehicle's X both fall out of where the ship's forward flap
 * ends up. \`starshipAssemble.ts\` owns that order; nothing else may write TW.
 */
import { MB, prism, sec_box, sec_i, sec_tube } from '../../procgen/sslib/meshbuilder'
import { V, Vec, cos, radians, sin, sqrt } from '../../procgen/sslib/mathkit'
import type { Pt3, Vec2 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'

/**
 * The literal's own fields plus the five the source derives from them on the
 * lines that follow, plus the two the assembly writes back. CHORD is a 4-tuple
 * because the source spreads it into \`sec_i(w, h, tw, tf)\`.
 */
interface TowerConfig {
  W: number
  SEC_H: number
  N_SEC: number
  BASE_Z: number
  BAYS: number
  COL: number
  MIDP: number
  CHORD: [number, number, number, number]
  DIAG_W: number
  DIAG_T: number
  ARM_Z: number
  ARM_LEN: number
  ARM_SPLAY: number
  ARM_PIVOT_Y: number
  ARM_D_ROOT: number
  ARM_D_TIP: number
  ARM_W_ROOT: number
  ARM_W_TIP: number
  QD_Z: number
  TOWER_X: number
  PAD_TS: number[]
  PAD_L: number
  PAD_H: number
  PAD_DZ: number
  PAD_SEAT: number
  VEHICLE_X: number
  HW: number
  TRUSS_TOP: number
  CROWN_TOP: number
  ROD_TOP: number
  BAY_H: number
}

`,
  [[1488, 1850]],
  [
    ['const TW = {\n  W: 12.20,', 'export const TW = {\n  W: 12.20,'],
    ['  PAD_DZ: 0.28, PAD_SEAT: 0.60, VEHICLE_X: 0.0\n};',
      '  PAD_DZ: 0.28, PAD_SEAT: 0.60, VEHICLE_X: 0.0\n} as TowerConfig;'],
    ['function pad_geom(t = TW.PAD_SEAT, sgn = 1){',
      'export function pad_geom(t = TW.PAD_SEAT, sgn = 1): [number, number, number, number] {'],
    ['const corners = () => { const H = TW.HW; return [[H, H], [-H, H], [-H, -H], [H, -H]]; };',
      'const corners = (): Vec2[] => { const H = TW.HW; return [[H, H], [-H, H], [-H, -H], [H, -H]]; };'],
    ['function faces(){\n  const c = corners(), out = [];',
      'function faces(): Array<[Vec2, Vec2, Vec]> {\n  const c = corners(), out: Array<[Vec2, Vec2, Vec]> = [];'],
    ['function railing(mb, pts, z, h, mat, post_every = 2.2){',
      'export function railing(mb: MB, pts: Vec2[], z: number, h: number, mat: number, post_every = 2.2): void {'],
    ['function build_truss(mb, m_col, m_beam, m_diag, m_grate){',
      'function build_truss(mb: MB, m_col: number, m_beam: number, m_diag: number, m_grate: number): void {'],
    ['function build_rails(mb, m_col, m_beam, m_dark, face_x = 1){',
      'function build_rails(mb: MB, m_col: number, m_beam: number, m_dark: number, face_x = 1): void {'],
    ['function build_crown(mb, m_col, m_beam, m_diag, m_grate, m_dark){',
      'function build_crown(mb: MB, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number): void {'],
    // EXPORTED (patch kind 1) so the runtime can build the carriage and each
    // arm into their OWN MB and animate them apart — the demo fuses all three
    // into one `Tower_Chopsticks` mesh, which cannot retract for a launch.
    // `MB.add_v` never welds, so a per-primitive split is lossless; see
    // starshipBuild.ts. The fused object is still emitted, for the parity harness.
    ['function chopstick(mb, pivot, yaw_deg, len, m_col, m_beam, m_diag, m_grate, m_dark){',
      'export function chopstick(mb: MB, pivot: Pt3, yaw_deg: number, len: number, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number): void {'],
    ['  const P = (t, sw, du) => {\n    const d = d_root + (d_tip - d_root) * t;',
      '  const P = (t: number, sw: number, du: number): Vec => {\n    const d = d_root + (d_tip - d_root) * t;'],
    ['  for (const sw of [-1, 1])\n    for (const du of [0, 1]){\n      const pts = [];',
      '  for (const sw of [-1, 1])\n    for (const du of [0, 1]){\n      const pts: Vec[] = [];'],
    ['  const rows = [];\n  for (let i = 0; i <= NB_; i++){\n    const t = i / NB_;',
      '  const rows: number[][] = [];\n  for (let i = 0; i <= NB_; i++){\n    const t = i / NB_;'],
    ['function carriage(mb, z, m_col, m_beam, m_diag, m_grate){',
      'export function carriage(mb: MB, z: number, m_col: number, m_beam: number, m_diag: number, _m_grate: number): void {'],
    ['function qd_arm(mb, z, reach, m_col, m_beam, m_diag, m_grate, m_dark, depth = 2.6, wid = 2.4){',
      'function qd_arm(mb: MB, z: number, reach: number, m_col: number, m_beam: number, m_diag: number, m_grate: number, m_dark: number, depth = 2.6, wid = 2.4): void {'],
    ['  const P = (t, sw, du) => {\n    const w = wid * (1.0 - 0.15 * t);',
      '  const P = (t: number, sw: number, du: number): Vec => {\n    const w = wid * (1.0 - 0.15 * t);'],
    ['  const rows = [];\n  for (let i = 0; i <= N; i++)', '  const rows: number[][] = [];\n  for (let i = 0; i <= N; i++)'],
    ['function towerBuild(){', 'export function towerBuild(): BuildObject[] {'],
    ['  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3, T_CONC = 4, T_BLK = 5;',
      '  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3;  /* slots 4 (concrete) and 5 (black) are in the list below but no face uses them */'],
    ['  const objs = [];\n  let mb;', '  const objs: BuildObject[] = [];\n  let mb: MB;'],
    ['  carriage(mb, TW.ARM_Z, T_MAIN, T_MAIN, T_DARK, T_GRATE);',
      '  carriage(mb, TW.ARM_Z, T_MAIN, T_MAIN, T_DARK, T_GRATE);  /* the source passes a grate slot the body never uses */'],
  ],
)

/* ==========================================================================
   src/starship/parts/olm.ts
   ========================================================================== */
emit(
  'src/starship/parts/olm.ts',
  `/**
 * The Orbital Launch Mount and its pad slab — \`ref_images/starship.html\` §7,
 * \`olm.py\`. GENERATED by tools/starship-gen.mjs; edit the generator.
 */
import { MB, lathe, prism, sec_box, sec_tube } from '../../procgen/sslib/meshbuilder'
import { TAU, cos, radians, sin } from '../../procgen/sslib/mathkit'
import type { Vec2, Vec3 } from '../../procgen/sslib/mathkit'
import type { BuildObject } from '../../procgen/sslib/evalmesh'
import { railing } from './tower'

`,
  [[1854, 1949]],
  [
    ['const OLM = {', 'export const OLM = {'],
    ['function olmBuild(){', 'export function olmBuild(): BuildObject[] {'],
    ['  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3, T_CONC = 4, T_CONCD = 5,\n        T_BLK = 6, T_SOOT = 7, T_ORG = 8, T_WHT = 9;',
      '  const T_MAIN = 0, T_DARK = 1, T_GRATE = 2, T_DKM = 3, T_CONC = 4, T_CONCD = 5,\n        T_BLK = 6, T_SOOT = 7;  /* slots 8 (orange) and 9 (white) are in the list below but no face uses them */'],
    ['  const objs = [];\n  let mb;', '  const objs: BuildObject[] = [];\n  let mb: MB;'],
    ['  const pts = [];\n  for (let k = 0; k < 40; k++)', '  const pts: Vec2[] = [];\n  for (let k = 0; k < 40; k++)'],
    ['    const top = [rt * cos(a), rt * sin(a), TABLE_BOT - 0.5];\n    const bot = [rb * cos(a), rb * sin(a), PLAT_Z];',
      '    const top: Vec3 = [rt * cos(a), rt * sin(a), TABLE_BOT - 0.5];\n    const bot: Vec3 = [rb * cos(a), rb * sin(a), PLAT_Z];'],
    ['      const p0 = [(rb + (rt - rb) * h0) * cos(a), (rb + (rt - rb) * h0) * sin(a), PLAT_Z + span * h0];\n      const p1 = [(rb + (rt - rb) * h1) * cos(a2), (rb + (rt - rb) * h1) * sin(a2), PLAT_Z + span * h1];',
      '      const p0: Vec3 = [(rb + (rt - rb) * h0) * cos(a), (rb + (rt - rb) * h0) * sin(a), PLAT_Z + span * h0];\n      const p1: Vec3 = [(rb + (rt - rb) * h1) * cos(a2), (rb + (rt - rb) * h1) * sin(a2), PLAT_Z + span * h1];'],
    ['      const p0b = [(rb + (rt - rb) * h1) * cos(a), (rb + (rt - rb) * h1) * sin(a), PLAT_Z + span * h1];\n      const p1b = [(rb + (rt - rb) * h0) * cos(a2), (rb + (rt - rb) * h0) * sin(a2), PLAT_Z + span * h0];',
      '      const p0b: Vec3 = [(rb + (rt - rb) * h1) * cos(a), (rb + (rt - rb) * h1) * sin(a), PLAT_Z + span * h1];\n      const p1b: Vec3 = [(rb + (rt - rb) * h0) * cos(a2), (rb + (rt - rb) * h0) * sin(a2), PLAT_Z + span * h0];'],
  ],
)

/* ==========================================================================
   src/starship/starshipAssemble.ts
   ========================================================================== */
emit(
  'src/starship/starshipAssemble.ts',
  `/**
 * The stack — \`ref_images/starship.html\` §8, \`assemble.py\`.
 * GENERATED by tools/starship-gen.mjs; edit the generator, not this file.
 *
 * ORDER MATTERS AND IS THE SOURCE'S. \`pad_geom()\` gives the catch pad's seat
 * on the arm; the vehicle's X follows from it; the arm's height then follows
 * from where the ship's forward flap underside passes that seat. Only after
 * both are written back into TW may \`towerBuild()\` run — it reads them.
 */
import { OLM, olmBuild } from './parts/olm'
import { TW, pad_geom, towerBuild } from './parts/tower'
import { BST, boosterBuild } from './parts/booster'
import { SHIP, hull_r, shipBuild } from './parts/ship'
import { radians, tan } from '../procgen/sslib/mathkit'
import type { BuildObject } from '../procgen/sslib/evalmesh'

export interface StarshipAssembly {
  objs: BuildObject[]
  VEH_X: number
  ARM_Z: number
  SHIP_Z: number
  DECK: number
}

`,
  [[1954, 1982]],
  [
    ['function assemble(){', 'export function assembleStarship(): StarshipAssembly {'],
    ['  const flap_underside = y_abs => {', '  const flap_underside = (y_abs: number): number => {'],
    ['  const objs = [];', '  const objs: BuildObject[] = [];'],
  ],
)

console.log(`\n${written} files, ${patched} patches applied.`)
